### PR TITLE
fix: add mutex to internal trace otel test variable

### LINKED ISSUE #9388: spanner/test: TestSpannerTracesWithOpenTelemetry failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: fc51cc2ac71e8fb0b3e381379dc343630ed441e7
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/5c02ac3b-2911-4293-889a-6bbe392689fa), [Sponge](http://sponge2/5c02ac3b-2911-4293-889a-6bbe392689fa)
status: failed

### PR DESCRIPTION
**Pull request by harshachinta**
Fixes #9388

The variable `OpenTelemetryTracingEnabled` is set by client library for testing purposes. However, there is a datarace condition that occurs when this variable is getting read in `trace` package and set in client library.
[Sigma link](https://btx-internal.corp.google.com/invocations/5c02ac3b-2911-4293-889a-6bbe392689fa/targets/cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fcontinuous%2Flatest-version/log)
Interestingly this is not reproducible on local with `-race` argument and not in presubmits too. But it failed in continuous build.

**Stack trace**
```
=== RUN   TestSpannerTracesWithOpenTelemetry
==================
WARNING: DATA RACE
Write at 0x0000026759b0 by goroutine 536:
  cloud.google.com/go/spanner/test.TestSpannerTracesWithOpenTelemetry()
      /tmpfs/src/google-cloud-go/spanner/test/opentelemetry/test/ot_traces_test.go:37 +0x6b
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x44

Previous read at 0x0000026759b0 by goroutine 500:
  cloud.google.com/go/internal/trace.TracePrintf()
      /tmpfs/src/google-cloud-go/internal/trace/trace.go:190 +0x72
  cloud.google.com/go/spanner.(*sessionClient).executeBatchCreateSessions()
      /tmpfs/src/google-cloud-go/spanner/sessionclient.go:310 +0x1c5a
  cloud.google.com/go/spanner.(*sessionClient).batchCreateSessions.func2()
      /tmpfs/src/google-cloud-go/spanner/sessionclient.go:234 +0x8c

Goroutine 536 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1648 +0x82a
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2054 +0x84
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x238
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2052 +0x896
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1925 +0xb57
  main.main()
      _testmain.go:57 +0x2bd

Goroutine 500 (finished) created at:
  cloud.google.com/go/spanner.(*sessionClient).batchCreateSessions()
      /tmpfs/src/google-cloud-go/spanner/sessionclient.go:234 +0x4ec
  cloud.google.com/go/spanner.(*sessionPool).growPoolLocked()
      /tmpfs/src/google-cloud-go/spanner/session.go:812 +0x187
  cloud.google.com/go/spanner.(*sessionPool).take()
      /tmpfs/src/google-cloud-go/spanner/session.go:1074 +0x788
  cloud.google.com/go/spanner.(*ReadOnlyTransaction).acquireSingleUse()
      /tmpfs/src/google-cloud-go/spanner/transaction.go:803 +0x553
  cloud.google.com/go/spanner.(*ReadOnlyTransaction).acquire()
      /tmpfs/src/google-cloud-go/spanner/transaction.go:780 +0x7b
  cloud.google.com/go/spanner.(*txReadOnly).ReadWithOptions()
      /tmpfs/src/google-cloud-go/spanner/transaction.go:228 +0x276
  cloud.google.com/go/spanner.(*txReadOnly).Read()
      /tmpfs/src/google-cloud-go/spanner/transaction.go:148 +0xb04
  cloud.google.com/go/spanner/test.TestOTMetrics_GFELatency()
      /tmpfs/src/google-cloud-go/spanner/test/opentelemetry/test/ot_metrics_test.go:288 +0xa4f
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x44
==================
    testing.go:1465: race detected during execution of test
--- FAIL: TestSpannerTracesWithOpenTelemetry (0.02s)
=== NAME  
    testing.go:1465: race detected during execution of test
```

### CODE REVIEW

**Review by rahul2393 — APPROVED** [review]

File: spanner/test/opentelemetry/test/ot_traces_test.go [hunk 1]
```diff
@@ -33,10 +33,16 @@ import (
 func TestSpannerTracesWithOpenTelemetry(t *testing.T) {
 	ctx := context.Background()
 	te := newOpenTelemetryTestExporter(false, true)
+	trace.OpenTelemetryTracingEnabledMu.RLock()
```
Comment (quartzmo) [inline spanner/test/opentelemetry/test/ot_traces_test.go:36]: I think it would be better for other users to make `OpenTelemetryTracingEnabled` and `OpenTelemetryTracingEnabledMu` private, and move these lock/unlock calls to a setter that controls access to `OpenTelemetryTracingEnabled`. (Be sure to keep the same `Do not access directly` warning.)

**Review by quartzmo — CHANGES_REQUESTED** [review]

File: spanner/test/opentelemetry/test/ot_traces_test.go (hunk 1 above)
Comment (quartzmo) [reply spanner/test/opentelemetry/test/ot_traces_test.go:36]: A setter and a getter, actually.

File: internal/trace/trace.go [hunk 2]
```diff
@@ -50,17 +51,23 @@ const (
 )
 
 var (
+	//
```
Comment (quartzmo) [inline internal/trace/trace.go:54]: Missing comment?

File: internal/trace/trace.go [hunk 3]
```diff
@@ -50,17 +51,23 @@ const (
...
-	//
-	// Do not access directly. Use instead IsOpenTelemetryTracingEnabled or
-	// IsOpenCensusTracingEnabled. Intended for use only in unit tests. Restore
-	// original value after each test.
-	OpenTelemetryTracingEnabled bool = strings.EqualFold(strings.TrimSpace(
+	openTelemetryTracingEnabled bool = strings.EqualFold(strings.TrimSpace(
 		os.Getenv(TelemetryPlatformTracingVar)), TelemetryPlatformTracingOpenTelemetry)
 )
 
+// Do not invoke SetOpenTelemetryTracingEnabledField directly. Set GOOGLE_API_GO_EXPERIMENTAL_TELEMETRY_PLATFORM_TRACING
```
Comment (quartzmo) [inline internal/trace/trace.go:63]: Go doc comments must always begin with the name of the code object. So prepend something like:

`// SetOpenTelemetryTracingEnabledField programmatically sets the value provided by GOOGLE_API_GO_EXPERIMENTAL_TELEMETRY_PLATFORM_TRACING for the purpose of unit testing.

File: internal/trace/trace.go [hunk 4]
```diff
@@ -59,6 +60,8 @@ var (
 	// original value after each test.
 	OpenTelemetryTracingEnabled bool = strings.EqualFold(strings.TrimSpace(
 		os.Getenv(TelemetryPlatformTracingVar)), TelemetryPlatformTracingOpenTelemetry)
+
+	OpenTelemetryTracingEnabledMu = sync.RWMutex{}
```
[the remark this answers is not in the document]
Comment (harshachinta) [reply internal/trace/trace.go]: Done.

File: internal/trace/trace.go (hunk 2 above)
Comment (harshachinta) [reply internal/trace/trace.go]: Added

**Review by quartzmo — APPROVED** [review]

File: internal/trace/trace.go (hunk 3 above)
Comment (harshachinta) [reply internal/trace/trace.go]: Done.

File: spanner/test/opentelemetry/test/ot_traces_test.go (hunk 1 above)
Comment (harshachinta) [reply spanner/test/opentelemetry/test/ot_traces_test.go]: Made the fields `OpenTelemetryTracingEnabled` and `OpenTelemetryTracingEnabledMu` private.
Instead `SetOpenTelemetryTracingEnabledField` can be used to edit this field for unit tests.

Q: Should we also suffix it with UnitTest? something like `SetOpenTelemetryTracingEnabledFieldForUnitTest`. Looks too longer though.
