### PR TITLE
fix(logging): init default retryer

### LINKED ISSUE #8408: logging: panic: runtime error: invalid memory address or nil pointer dereference
**Client**

e.g. Cloud Logging

**Environment**

e.g. Alpine Docker on GKE

**Go Environment**

$ go version
$ go env

**Code**

https://chromium-review.googlesource.com/c/infra/infra/+/4769930/2/go/src/infra/go.mod

**Expected behavior**

Don't panic.

**Actual behavior**

https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8773108843220167633/+/u/Build_all_without_remote_cache/stdout

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xab79b8]

goroutine 177 [running]:
cloud.google.com/go/logging.(*loggerRetryer).Retry(0xc03d12d130, {0x1020d20, 0xc09477e630})
	cloud.google.com/go/logging@v1.8.0/logging.go:275 +0x78
github.com/googleapis/gax-go/v2.invoke({0x102b460, 0xc0992178f0}, 0xc0404e5e90, {0xc03d12d140, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0xdf8475800}, ...)
	github.com/googleapis/gax-go/v2@v2.12.0/invoke.go:108 +0x21d
github.com/googleapis/gax-go/v2.Invoke({0x102b460, 0xc0992178f0}, 0xc0404e5e70?, {0xc0847b7900, 0x3, 0xc099217830?})
	github.com/googleapis/gax-go/v2@v2.12.0/invoke.go:50 +0xdd
cloud.google.com/go/logging/apiv2.(*gRPCClient).WriteLogEntries(0xc000050540, {0x102b428?, 0xc099217830?}, 0xc055371420, {0xc03d12d160, 0x1, 0xc0404e5f10?})
	cloud.google.com/go/logging@v1.8.0/apiv2/logging_client.go:360 +0x192
cloud.google.com/go/logging/apiv2.(*Client).WriteLogEntries(...)
	cloud.google.com/go/logging@v1.8.0/apiv2/logging_client.go:225
cloud.google.com/go/logging.(*Logger).writeLogEntries(0xc000720c00, {0xc03221b800, 0x3e8, 0x500})
	cloud.google.com/go/logging@v1.8.0/logging.go:738 +0x23b
cloud.google.com/go/logging.(*Client).Logger.func2({0xd15ec0?, 0xc07f8d21f8?})
	cloud.google.com/go/logging@v1.8.0/logging.go:298 +0x45
google.golang.org/api/support/bundler.(*Bundler).handle(0xc0000ea420, 0x0?)
	google.golang.org/api@v0.136.0/support/bundler/bundler.go:324 +0x4a
created by google.golang.org/api/support/bundler.(*Bundler).enqueueCurBundle
	google.golang.org/api@v0.136.0/support/bundler/bundler.go:179 +0x14d
```

**Additional context**

Started after upgrading to v1.8.0

### PR DESCRIPTION
**Pull request by noahdietz**
Manually copies default retry configuration from the GAPIC `WriteLogEntries` default call options to be used as the default retry logic for the `loggerRetryer`. This is what I assume was intended in #7509, but which was not actually done, resulting in the `nil` panics reported by users (as the `defaultRetryer` was an uninitialized `interface`).

Fixes #8408

### CODE REVIEW

File: logging/logging.go [hunk 1]
```diff
@@ -264,12 +267,28 @@ type loggerRetryer struct {
...
+	return r
+}
+
 func (r *loggerRetryer) Retry(err error) (pause time.Duration, shouldRetry bool) {
 	s, ok := status.FromError(err)
 	if !ok {
 		return r.defaultRetryer.Retry(err)
 	}
-	if s.Code() == codes.Internal && strings.Contains(s.Message(), "string field contains invalid UTF-8") {
+	if s.Code() == codes.Internal && strings.Contains(s.Message(), utfErrorString) {
```
Comment (codyoss) [inline logging/logging.go:291]: nit: the internal check is not needed here and/or codes above can be reduced to match.

**Review by codyoss — APPROVED** [review]

File: logging/logging.go (hunk 1 above)
Comment (noahdietz) [reply logging/logging.go]: I removed the `codes.Internal` check. Good point.
