### PR TITLE
fix(internal): add autogenerated header to snippets

### LINKED ISSUE #4260: internal/gensnippets: include comment indicating code is autogenerated
Can we include a comment near the top of the file indicating that the code is autogenerated? I believe this is the (somewhat recently) accepted format of such comments: https://golang.org/cmd/go/#hdr-Generate_Go_files_by_processing_source. I read in the PRD that this should be indicated and noticed it hadn't been added already.

For GAPICs it is `// Code generated by protoc-gen-go_gapic. DO NOT EDIT.` just under the license block.

### PR DESCRIPTION
**Pull request by noahdietz**
Fixes #4260

### CODE REVIEW

File: internal/gapicgen/gensnippets/gensnippets.go [hunk 1]
```diff
@@ -268,4 +268,6 @@ const licenseHeader string = `// Copyright %v Google LLC
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
+// Code generated by cloud.google.com/go/internal/gapicgen/gensnippets. DO NOT EDIT.
```
Comment (noahdietz) [inline internal/gapicgen/gensnippets/gensnippets.go:271]: We could exclude the `by cloud.google.com/go/internal/gapicgen/gensnippets` altogether per the documented rule.

**Review by codyoss — APPROVED** [review]
LGTM, thank you!

**Comment by tbpg** [comment]
Thank you!
