### PR TITLE
test(pubsub): dedupe by message data in ordering keys json test

### LINKED ISSUE #8520: pubsub: many tests failed
Many tests failed at the same time in this package.

* I will close this issue when there are no more failures in this package _and_
  there is at least one pass.
* No new issues will be filed for this package until this issue is closed.
* If there are already issues for individual test cases, I will close them when
  the corresponding test passes. You can close them earlier, if you prefer, and
  I won't reopen them while this issue is still open.

Here are the tests that failed:
* TestFlowControllerCancel (#7072)
* TestFlowControllerLargeRequest (#7073)
* TestFlowControllerNoStarve (#7074)
* TestFlowControllerSaturation (#7075)
* TestFlowControllerUnboundedCount (#7076)
* TestFlowControllerUnboundedCount2 (#7077)
* TestFlowControllerUnboundedBytes (#7078)
* TestIntegration_All (#7079)
* TestIntegration_CancelReceive (#8195)
* TestIntegration_CreateSubscription_NeverExpire
* TestIntegration_UpdateSubscription
* TestIntegration_UpdateSubscription_ExpirationPolicy
* TestIntegration_UpdateTopicLabels
* TestIntegration_PublicTopic
* TestIntegration_Errors (#8431)
* TestIntegration_MessageStoragePolicy_TopicLevel
* TestIntegration_MessageStoragePolicy_ProjectLevel
* TestIntegration_CreateTopic_KMS
* TestIntegration_CreateTopic_MessageStoragePolicy
* TestIntegration_OrderedKeys_JSON (#6001)

-----
commit: a05b6edb5795104a08a41a45be04dc3d2535eff2
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/819f896a-f3fa-4d7a-ac59-109be3b86f42), [Sponge](http://sponge2/819f896a-f3fa-4d7a-ac59-109be3b86f42)
status: failed

### PR DESCRIPTION
**Pull request by hongalex**
Closes #8520

See comments in above issue for how this PR fixes this test

### CODE REVIEW

File: pubsub/integration_test.go [hunk 1]
```diff
@@ -1263,11 +1264,17 @@ func TestIntegration_OrderedKeys_JSON(t *testing.T) {
...
-			ID:          msg,
+		r := topic.Publish(ctx, &Message{
 			Data:        []byte(msg),
 			OrderingKey: key,
 		})
+		go func() {
+			_, err := r.Get(ctx)
+			if err != nil {
+				// Can't fail inside goroutine, so just log the error
+				log.Printf("publish error for message(%s): %v", msg, err)
```
Comment (noahdietz) [inline pubsub/integration_test.go:1275]: Might be worth just using the [test logger](https://pkg.go.dev/testing#T.Logf):
```suggestion
				t.Logf("publish error for message(%s): %v", msg, err)
```

File: pubsub/integration_test.go [hunk 2]
```diff
@@ -21,6 +21,7 @@ import (
 	"errors"
 	"fmt"
 	"io/ioutil"
+	"log"
```
Comment (noahdietz) [inline pubsub/integration_test.go:24]:
```suggestion
	"io/ioutil"
```
Goes with the other change suggested, but feel free to do them in your own single commit

**Review by noahdietz — APPROVED** [review]
Just one nit. Approving as admin to unblock failed test resolution.
