### PR TITLE
test(spanner): fix flaky TestMaintainer test

### LINKED ISSUE #3230: spanner: TestMaintainer failed
Note: #2354 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 299b803aaee9a0dc0b2ec8c81fac66341045b8b2
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/bdf8c7e9-ef9b-4e68-96ea-ac4aa88d9ae4), [Sponge](http://sponge2/bdf8c7e9-ef9b-4e68-96ea-ac4aa88d9ae4)
status: failed
<details><summary>Test output</summary><br><pre>session_test.go:1581: numOpened sessions mismatch
    Got: 29
    Want: 30</pre></details>

### PR DESCRIPTION
**Pull request by olavloite**
Fixes #3230

### CODE REVIEW

File: spanner/session_test.go [hunk 1]
```diff
@@ -1574,12 +1574,20 @@ func TestMaintainer(t *testing.T) {
...
-	sp.mu.Lock()
-	g, w := sp.numOpened, sp.MinOpened+sp.incStep
-	sp.mu.Unlock()
-	if g != w {
-		t.Fatalf("numOpened sessions mismatch\nGot: %d\nWant: %d", g, w)
-	}
+	// It is possible that we need to wait a little before all sessions have been created.
+	// We requested 20 sessions, but the default step that BatchCreateSessions will use is
+	// 25 sessions. It is therefore possible that 20 sessions have been returned to the
+	// test, without all the sessions that have been requested from the server have been
```
Comment (hengfengli) [inline spanner/session_test.go:1580]: nits: consider to rephrase the last sentence. 

> It is therefore possible that 20 sessions have been returned to the test, without all the sessions that have been requested from the server have been added to the pool.

I think this means that when we execute the check, some sessions are still not returned to the pool (< 5 + 25) yet so that we need to wait for a bit.

**Review by hengfengli — APPROVED** [review]
LGTM.

File: spanner/session_test.go (hunk 1 above)
Comment (olavloite) [reply spanner/session_test.go]: Yep, that comment was not really clarifying very much... I've changed it into a better description of what is actually happening.
