### PR TITLE
spanner/spansql: restructure types and parsing for column options

### LINKED ISSUE #2621: spansql: AlterColumn produces invalid SQL when there is an AllowCommitTimestamp OPTION
**Code**

```go
package main

import (
  "fmt"

  "cloud.google.com/go/spanner/spansql"
)

func main() {
  allow := true
  stmt := spansql.AlterTable{
    Name: "Tasks",
    Alteration: spansql.AlterColumn{
      Def: spansql.ColumnDef{
        Name: "LastUpdate",
        Type: spansql.Type{Base: spansql.Timestamp},
        AllowCommitTimestamp: &allow,
      },
    },
  }
  fmt.Println(stmt.SQL())
}
```

**Expected behavior**

`AlterColumn` should only alter the column type:

```sql
ALTER TABLE Tasks ALTER COLUMN LatestUpdate TIMESTAMP
```

To support setting options, there should probably be a separate type (maybe something like `AlterOptions`) that produces:

```sql
ALTER TABLE Tasks ALTER COLUMN LatestUpdate SET OPTIONS (allow_commit_timestamp = true)
```

**Actual behavior**

The resulting statement is invalid and rejected by spanner:

```sql
ALTER TABLE Tasks ALTER COLUMN LatestUpdate TIMESTAMP OPTIONS (allow_commit_timestamp = true);
```

```
Error: rpc error: code = InvalidArgument desc = Error parsing Spanner DDL statement: 
ALTER TABLE Tasks ALTER COLUMN LatestUpdateTime TIMESTAMP OPTIONS (allow_commit_timestamp = true) : 
Syntax error on line 1, column ##: Expecting 'EOF' but found 'OPTIONS'
```

### PR DESCRIPTION
**Pull request by dsymonds**
Column options appear in a few different places:
	CREATE TABLE
        ALTER TABLE ... ADD COLUMN
        ALTER TABLE ... ALTER COLUMN

In the first two places, the entire column is being defined, and the
options may appear without a leading "SET". The third place may
explicitly set options using "SET". In all cases, the options
specification is itself the same, so extract that into its own type,
ColumnOptions, and add distinguished ColumnAlteration types so the
`ALTER TABLE ... ALTER COLUMN` form may be correctly parsed and
formatted.

This change is backward incompatible, but should only affect those using
(defining or parsing) column options.

Fixes #2621.

### CODE REVIEW

File: spanner/spansql/sql_test.go [hunk 1]
```diff
@@ -190,6 +190,22 @@ func TestSQL(t *testing.T) {
 			"ALTER TABLE Ta SET ON DELETE CASCADE",
 			reparseDDL,
 		},
+		{
+			&AlterTable{
```
Comment (hengfengli) [inline spanner/spansql/sql_test.go:194]: Should we add a test for `SetColumnType` as well?

Comment (dsymonds) [reply spanner/spansql/sql_test.go:194]: Sure, done.

**Comment by wyardley** [comment]
Can someone cut a release for this? This is resolving the issue above for me, but still doesn't appear to be in the latest released version of the module.

**Comment by hengfengli** [comment]
I'll cut a release soon.
