### PR TITLE
chore(datastore): fix for flaky integration tests

### LINKED ISSUE #6938: datastore: TestIntegration_GetWithReadTime failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 924074139a086aec7f12572d05909ee0b54e21f5
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/c884c352-68b8-45a9-9578-2d8eb4b16957), [Sponge](http://sponge2/c884c352-68b8-45a9-9578-2d8eb4b16957)
status: failed
<details><summary>Test output</summary><br><pre>    integration_test.go:222: client.Get: rpc error: code = InvalidArgument desc = timestamp cannot have more than microseconds precision</pre></details>

### LINKED ISSUE #6939: datastore: TestIntegration_GetMulti failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 924074139a086aec7f12572d05909ee0b54e21f5
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/c884c352-68b8-45a9-9578-2d8eb4b16957), [Sponge](http://sponge2/c884c352-68b8-45a9-9578-2d8eb4b16957)
status: failed
<details><summary>Test output</summary><br><pre>    integration_test.go:330: client.GetMulti got *status.Error, expected MultiError</pre></details>

### PR DESCRIPTION
**Pull request by telpirion**
Fixes #6939
Fixes #6938

### CODE REVIEW

File: datastore/integration_test.go [hunk 1]
```diff
@@ -199,29 +200,49 @@ func TestIntegration_Basics(t *testing.T) {
...
+		tm := ReadTime(time.Now())
+
+		client.WithReadOptions(tm)
+
+		// If the Entity isn't available at the requested read time, we get
+		// a "datastore: no such entity" error. The ReadTime is otherwise not
+		// exposed in anyway in the response.
+		err = client.Get(ctx, k, &got)
+		if err != nil {
+			t.Errorf("client.Get: %v", err)
```
Comment (quartzmo) [inline datastore/integration_test.go:242]: Should this be `r.Errorf` to ensure the retry works correctly?

Btw, have you observed the retries working?

File: datastore/integration_test.go [hunk 2]
```diff
@@ -199,29 +200,49 @@ func TestIntegration_Basics(t *testing.T) {
...
+	ctx, cancel := context.WithTimeout(context.Background(), time.Second*20)
 	client := newTestClient(ctx, t)
+	defer cancel()
 	defer client.Close()
 
-	type X struct {
-		I int
-		S string
-		T time.Time
-		U interface{}
```
Comment (quartzmo) [inline datastore/integration_test.go:210]: Was this a duplicate, shadowing declaration of `X`?

Comment (quartzmo) [reply datastore/integration_test.go:210]: nm, I see now that `X` usages were removed (I mixed up the green and red).

File: datastore/integration_test.go [hunk 3]
```diff
@@ -199,29 +200,49 @@ func TestIntegration_Basics(t *testing.T) {
...
+	if _, err := tx.Put(k, &rt1); err != nil {
+		t.Fatalf("Transaction.Put: %v\n", err)
 	}
 
+	if _, err := tx.Commit(); err != nil {
+		t.Fatalf("Transaction.Commit: %v\n", err)
+	}
+
+	// Wait a little bit for eventual consistency to catch up.
+	time.Sleep(time.Duration(10 * math.Pow(10, 9)))
```
Comment (quartzmo) [inline datastore/integration_test.go:229]: Is it really worth waiting 10s every time? I think this is only worth it if it's guaranteed to take that long, otherwise might as well try right away, or after a shorter wait.

Comment (telpirion) [reply datastore/integration_test.go:229]: I tried several different time lengths from 1-10 seconds to ensure consistent test success. 10s was the lowest value that seemed to work every time (locally).

Comment (telpirion) [reply datastore/integration_test.go:229]: You know what, it looks like the issue was that I didn't hook into the retries correctly :). Nice catch!

File: datastore/integration_test.go (hunk 1 above)
Comment (telpirion) [reply datastore/integration_test.go:242]: Done. Nice catch!

**Review by quartzmo — APPROVED** [review]
