### PR TITLE
test(storage): refactor RequesterPays test to avoid rate limits

### LINKED ISSUE #4720: storage: TestIntegration_RequesterPays failed
Note: #4474 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: ffa903eeec61aa3869e5220e2f09371127b5c393
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/561be150-624a-4ace-9486-45e3dae6c277), [Sponge](http://sponge2/561be150-624a-4ace-9486-45e3dae6c277)
status: failed
<details><summary>Test output</summary><br><pre>integration_test.go:2561: default object acl set: googleapi: Error 429: The project exceeded the rate limit for bucket operations (buckets creating, updating and deleting)., rateLimitExceeded, want nil
    confirm that kokoro@dulcet-port-762.iam.gserviceaccount.com is an Owner on dulcet-port-762
integration_test.go:2584: default object acl set: got googleapi: Error 429: The project exceeded the rate limit for bucket operations (buckets creating, updating and deleting)., rateLimitExceeded, want nil
    confirm that kokoro@gcloud-golang-firestore-tests.iam.gserviceaccount.com is an Editor on gcloud-golang-firestore-tests and that that project has billing enabled
integration_test.go:2593: default object acl set: got error googleapi: Error 429: The project exceeded the rate limit for bucket operations (buckets creating, updating and deleting)., rateLimitExceeded, want code 403
    confirm that kokoro@gcloud-golang-firestore-tests.iam.gserviceaccount.com is NOT an Editor on veener-jba
integration_test.go:2561: default object acl delete: googleapi: Error 429: The project exceeded the rate limit for bucket operations (buckets creating, updating and deleting)., rateLimitExceeded, want nil
    confirm that kokoro@dulcet-port-762.iam.gserviceaccount.com is an Owner on dulcet-port-762
integration_test.go:2569: default object acl delete: got googleapi: Error 429: The project exceeded the rate limit for bucket operations (buckets creating, updating and deleting)., rateLimitExceeded, want nil
integration_test.go:2576: default object acl delete: got error googleapi: Error 429: The project exceeded the rate limit for bucket operations (buckets creating, updating and deleting)., rateLimitExceeded with code 429, want code 400
    confirm that kokoro@gcloud-golang-firestore-tests.iam.gserviceaccount.com is NOT an Owner on dulcet-port-762
integration_test.go:2576: object acl delete: got error googleapi: Error 429: The rate of change requests to the object go-integration-test-20210902-70225704308686-0013/acl-go-testgo-integration-test-20210902-70225704308686-0015 exceeds the rate limit. Please reduce the rate of create, update, and delete requests., rateLimitExceeded with code 429, want code 400
    confirm that kokoro@gcloud-golang-firestore-tests.iam.gserviceaccount.com is NOT an Owner on dulcet-port-762
integration_test.go:2593: object acl delete: got error googleapi: Error 429: The rate of change requests to the object go-integration-test-20210902-70225704308686-0013/acl-go-testgo-integration-test-20210902-70225704308686-0015 exceeds the rate limit. Please reduce the rate of create, update, and delete requests., rateLimitExceeded, want code 403
    confirm that kokoro@gcloud-golang-firestore-tests.iam.gserviceaccount.com is NOT an Editor on veener-jba</pre></details>

### PR DESCRIPTION
**Pull request by BrennaEpp**
* Uses a different object per test
* Will be easier to refactor if we still hit rate limits
* Fixes #4720

### CODE REVIEW

File: storage/integration_test.go [hunk 1]
```diff
@@ -2742,24 +2742,34 @@ func TestIntegration_RequesterPays(t *testing.T) {
...
-	defer client.Close()
+	// Start client with mainUserEmail creds
+	mainUserClient := testConfig(ctx, t)
+	defer mainUserClient.Close()
 
-	h := testHelper{t}
+	// Get user emails from credentials
+	jwt, err := testutil.JWTConfig()
+	if err != nil {
+		t.Fatal(err)
```
Comment (tritone) [inline storage/integration_test.go:2755]: Add some text to the errors here and below to make it clear where the failure occurred.

File: storage/integration_test.go [hunk 2]
```diff
@@ -2742,24 +2742,34 @@ func TestIntegration_RequesterPays(t *testing.T) {
...
+	}
+	// 1a. account that has permissions on the project that owns the bucket
+	mainUserEmail := jwt.Email
 
-	// Set project IDs
-	const noPermissionsProjID = "veener-jba" // a third project, one on which the user does NOT have Editor permission
+	// 1b. account with permissions on the second project but not on the project that owns the bucket
```
Comment (tritone) [inline storage/integration_test.go:2760]: Are these numberings corresponding to particular test cases? I think they are duplicated in your test case descriptions below so you can probably just delete them.

File: storage/integration_test.go [hunk 3]
```diff
@@ -2799,197 +2797,158 @@ func TestIntegration_RequesterPays(t *testing.T) {
...
+		expectSuccess bool
+		wantErrorCode int
+		errorMessage  string
+	}{
+		{
+			desc:          "user is Owner on the project that owns the bucket",
+			client:        mainUserClient,
+			userProject:   nil,
+			expectSuccess: true, // by the rule permitting access by owners of the containing bucket
+			errorMessage:  fmt.Sprintf("confirm that %s is an Owner on %s", mainUserEmail, mainProjectID),
```
Comment (tritone) [inline storage/integration_test.go:2823]: Checking the specific error messages is probably too brittle. We can check status code and (potentially) reason but the full message is subject to change. Also, why is there an error message on cases which are expected to succeed?

File: storage/integration_test.go [hunk 4]
```diff
@@ -2799,197 +2797,158 @@ func TestIntegration_RequesterPays(t *testing.T) {
...
+			checkforErrors("object acl set", bucket.Object(objectName2).ACL().Set(ctx, entity, RoleReader))
+			_, err = bucket.Object(objectName2).ACL().List(ctx)
+			checkforErrors("object acl list", err)
+			checkforErrors("object acl list", bucket.Object(objectName2).ACL().Delete(ctx, entity))
+
+			// Copy and compose
+			_, err = bucket.Object("copy").CopierFrom(bucket.Object(objectName)).Run(ctx)
+			checkforErrors("copy", err)
+			_, err = bucket.Object("compose").ComposerFrom(bucket.Object(objectName), bucket.Object("copy")).Run(ctx)
+			checkforErrors("compose", err)
```
Comment (tritone) [inline storage/integration_test.go:2933]: It seems a bit overkill to check so many operations, but I guess that's what the test does currently?

**Review by tritone — COMMENTED** [review]
Thanks for working on this!

File: storage/integration_test.go (hunk 3 above)
Comment (BrennaEpp) [reply storage/integration_test.go:2823]: So this error message is the one we return in case of error, not an error we are checking for.
For each test case we want specific conditions to hold (for example, mainUser should be an Owner), otherwise the test case won't pass, so we add that condition (defined in `errorMessage`) to the output to help debugging in case of test failure. 
These were the messages from the original test. I can see where this is confusing though - do you have any suggestions to improve how we do this?

File: storage/integration_test.go (hunk 4 above)
Comment (BrennaEpp) [reply storage/integration_test.go:2933]: Yes, that is what the current test does.

File: storage/integration_test.go (hunk 2 above)
Comment (BrennaEpp) [reply storage/integration_test.go:2760]: These numberings correspond to the numbers in the comment at the beginning of the test. I added them to make it clearer where we are getting each entity defined in the comment from.

**Review by tritone — APPROVED** [review]
