### PR TITLE
fix(pubsub): fix default stream ack deadline seconds

### LINKED ISSUE #3397: pubsub: TestIntegration_All failed
Note: #2929 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 45131b6c526ded2964ffd067c4a5420d508f0b1a
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/bc31234d-243b-4a00-a684-5e0dded393d1), [Sponge](http://sponge2/bc31234d-243b-4a00-a684-5e0dded393d1)
status: failed
<details><summary>Test output</summary><br><pre>integration_test.go:308: MaxOutstandingMessages=0, Synchronous=false, messages got: map[], messages want: map[1819408950098894:{ID:1819408950098894 Data:a message with an index 0 -  Attributes:map[foo:bar]} 1819408950098900:{ID:1819408950098900 Data:a message with an index 6 -  Attributes:map[foo:bar]} 1819408950098902:{ID:1819408950098902 Data:a message with an index 8 -  Attributes:map[foo:bar]} 1819408950098903:{ID:1819408950098903 Data:a message with an index 9 -  Attributes:map[foo:bar]} 1819408950098895:{ID:1819408950098895 Data:a message with an index 1 -  Attributes:map[foo:bar]} 1819408950098896:{ID:1819408950098896 Data:a message with an index 2 -  Attributes:map[foo:bar]} 1819408950098897:{ID:1819408950098897 Data:a message with an index 3 -  Attributes:map[foo:bar]} 1819408950098898:{ID:1819408950098898 Data:a message with an index 4 -  Attributes:map[foo:bar]} 1819408950098899:{ID:1819408950098899 Data:a message with an index 5 -  Attributes:map[foo:bar]} 1819408950098901:{ID:1819408950098901 Data:a message with an index 7 -  Attributes:map[foo:bar]}]
/usr/local/go/src/testing/testing.go:546 +0x1c6
/usr/local/go/src/testing/testing.go:616 +0x7d
/tmpfs/src/google-cloud-go/pubsub/integration_test.go:484 +0x1c0
/tmpfs/src/google-cloud-go/pubsub/integration_test.go:477 +0x539</pre></details>

### LINKED ISSUE #3398: pubsub: TestIntegration_CancelReceive failed
Note: #1841 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 45131b6c526ded2964ffd067c4a5420d508f0b1a
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/bc31234d-243b-4a00-a684-5e0dded393d1), [Sponge](http://sponge2/bc31234d-243b-4a00-a684-5e0dded393d1)
status: failed
<details><summary>Test output</summary><br><pre>integration_test.go:490: Waited 60 seconds for Receive to finish, should have finished sooner</pre></details>

### LINKED ISSUE #3399: pubsub: TestIntegration_OrderedKeys_Basic failed
Note: #3009 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 45131b6c526ded2964ffd067c4a5420d508f0b1a
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/bc31234d-243b-4a00-a684-5e0dded393d1), [Sponge](http://sponge2/bc31234d-243b-4a00-a684-5e0dded393d1)
status: failed
<details><summary>Test output</summary><br><pre>integration_test.go:1182: timed out after 5s waiting for item 0</pre></details>

### PR DESCRIPTION
**Pull request by hongalex**
A error was made in #3367 when using the default MaxExtensionPeriod of 0 seconds. This also made the default stream ack deadline seconds 0, which means messages will always expire and messages will never be successfully delivered. This PR reverts to the previous default of 60 seconds if MaxExtensionPeriod is disabled.

This issue fixes #3397, fixes #3398, fixes #3399

### CODE REVIEW

File: pubsub/pullstream.go [hunk 1]
```diff
@@ -47,10 +47,16 @@ func newPullStream(ctx context.Context, streamingPull streamingPullFunc, subName
...
 				recordStat(ctx, StreamRequestCount, 1)
+				streamAckDeadline := int32(maxDurationPerLeaseExtension / time.Second)
+				// By default, maxDurationPerLeaseExtension, aka MaxExtensionPeriod, is disabled,
+				// so in these cases, use a healthy default of 60 seconds.
+				if streamAckDeadline <= 0 {
+					streamAckDeadline = 60
+				}
 				err = spc.Send(&pb.StreamingPullRequest{
 					Subscription: subName,
 					// We modack messages when we receive them, so this value doesn't matter too much.
```
Comment (tmdiep) [inline pubsub/pullstream.go:58]: Nit: perhaps remove/reword this sentence, since it does seem to matter somewhat :)

**Review by tmdiep — APPROVED** [review]
