### PR TITLE
fix(spanner): allow encoding struct with custom types to mutation

### LINKED ISSUE #853: Spanner: Support Custom Types that point back to supported types
It would be great to use custom types/structs in db object structs that point back to supported types.
**Motivation:** Custom types enable custom type marsheling and unmarsheling for e.g. JSON or CSV that aren't supported by default.

**Example:**
```go
type blobField []byte
type dbProductInfo struct {
    ProductID  int64     `spanner:"ProductID"`
    UpdateDate time.Time `spanner:"UpdateDate"`
    Data       blobField `spanner:"Data"`
}
```

**Current Behavior:** Cloud Spanner Client Error: spanner: code = "InvalidArgument", desc = "client doesn't support type main.blobField"

**Desired Behavior:** It should just work

### PR DESCRIPTION
**Pull request by olavloite**
Encoding a struct containing custom base types was not permitted by the client library, while the underlying support had been added.

Fixes #853

### CODE REVIEW

File: spanner/client_test.go [hunk 1]
```diff
@@ -1480,6 +1480,114 @@ func TestClient_WriteStructWithPointers(t *testing.T) {
...
+	}
+	requests := drainRequestsFromServer(server.TestSpanner)
+	for _, req := range requests {
+		if commit, ok := req.(*sppb.CommitRequest); ok {
+			if g, w := len(commit.Mutations), 2; w != g {
+				t.Fatalf("mutation count mismatch\nGot: %v\nWant: %v", g, w)
+			}
+			insert := commit.Mutations[0].GetInsert()
+			// The first insert should contain empty values and empty arrays
+			for i := 1; i < len(insert.Values[0].Values); i += 2 {
```
Comment (hengfengli) [inline spanner/client_test.go:1552]: Can we define a variable for `insert.Values[0]`? Because it has been reused in multiple places.

File: spanner/client_test.go [hunk 2]
```diff
@@ -1480,6 +1480,114 @@ func TestClient_WriteStructWithPointers(t *testing.T) {
...
+				// The array columns should not be NULL.
+				g, wList := insert.Values[0].Values[i+1].GetKind(), &structpb.Value_ListValue{}
+				if _, ok := g.(*structpb.Value_ListValue); !ok {
+					t.Fatalf("type mismatch\nGot: %v\nWant: %v", g, wList)
+				}
+			}
+
+			// The second insert should contain all non-NULL values.
+			insert = commit.Mutations[1].GetInsert()
+			for i := 1; i < len(insert.Values[0].Values); i += 2 {
```
Comment (hengfengli) [inline spanner/client_test.go:1567]: Same here.

File: spanner/client_test.go (hunk 1 above)
Comment (olavloite) [reply spanner/client_test.go]: Good point, done.

File: spanner/client_test.go (hunk 2 above)
Comment (olavloite) [reply spanner/client_test.go]: Done.
