### PR TITLE
test(storage): fixes bugs introduced in #6510

### LINKED ISSUE #6576: storage: TestIntegration_Objects failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: c85704f4284626ce728cb48f3b130f2ce2a0165e
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/e23d1a04-550b-4d0b-9e59-04f2dad3298d), [Sponge](http://sponge2/e23d1a04-550b-4d0b-9e59-04f2dad3298d)
status: failed
<details><summary>Test output</summary><br><pre>    integration_test.go:1877: second deletion of copy-obj1 = googleapi: Error 503: We encountered an internal error. Please try again., backendError; want ErrObjectNotExist</pre></details>

### LINKED ISSUE #6577: storage: TestIntegration_BucketPolicyOnly failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: c220ca27ff705ce1cf32ddbf1f40f945cf7f59de
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/b9d4310a-e1eb-4837-a4df-49a67da6c3b3), [Sponge](http://sponge2/b9d4310a-e1eb-4837-a4df-49a67da6c3b3)
status: failed
<details><summary>Test output</summary><br><pre>    integration_test.go:654: ACL.List: object ACL list failed: googleapi: Error 400: Cannot get legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access, invalid
    integration_test.go:658: containsACL: expected ACLs [] to include custom ACL entity user-test@example.com</pre></details>

### LINKED ISSUE #6578: storage: TestIntegration_UniformBucketLevelAccess failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: c220ca27ff705ce1cf32ddbf1f40f945cf7f59de
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/b9d4310a-e1eb-4837-a4df-49a67da6c3b3), [Sponge](http://sponge2/b9d4310a-e1eb-4837-a4df-49a67da6c3b3)
status: failed
<details><summary>Test output</summary><br><pre>    integration_test.go:734: ACL.List: object ACL list failed: googleapi: Error 400: Cannot get legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access, invalid
    integration_test.go:738: containsACL: expected ACLs [] to include custom ACL entity user-test@example.com</pre></details>

### LINKED ISSUE #6579: storage: TestIntegration_ACL failed
Note: #6379 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: c220ca27ff705ce1cf32ddbf1f40f945cf7f59de
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/4a304d7d-ec92-463d-a84e-889c3db50f72), [Sponge](http://sponge2/4a304d7d-ec92-463d-a84e-889c3db50f72)
status: failed
<details><summary>Test output</summary><br><pre>    integration_test.go:2373: hasRule: object ACL missing {Entity:domain-google.com EntityID: Role:READER Domain:google.com Email: ProjectTeam:<nil>}
    integration_test.go:2377: object ACL: could not delete entity domain-google.com</pre></details>

### PR DESCRIPTION
**Pull request by BrennaEpp**
Fixes #6579, fixes #6578, fixes #6577, fixes #6576

### CODE REVIEW

File: storage/integration_test.go [hunk 1]
```diff
@@ -659,6 +657,14 @@ func TestIntegration_BucketPolicyOnly(t *testing.T) {
 	}
 }
 
+func retryOnNilAndTransientErrs(err error) bool {
+	return err == nil || ShouldRetry(err)
+}
+func retryOn400AndTransientErrs(err error) bool {
+	var e *googleapi.Error
+	return ShouldRetry(err) || errors.As(err, &e) && e.Code == 400
```
Comment (tritone) [inline storage/integration_test.go:665]: Do we see any of these tests failing with other codes (e.g. 401 or 403)? Would be good to double check.

**Review by tritone — APPROVED** [review]

**Review by tritone — APPROVED** [review]
