### PR TITLE
test(storage): run metrics test only in grpc

### LINKED ISSUE #11397: storage: TestIntegration_MetricsEnablement failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: b4d86a52bd319a602115cdb710a743c71494a88b
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/7310b833-79fa-4e3a-8680-5b08ce8c4be6), [Sponge](http://sponge2/7310b833-79fa-4e3a-8680-5b08ce8c4be6)
status: failed

### PR DESCRIPTION
**Pull request by cojenco**
`TestIntegration_MetricsEnablement` performs a list object and no reads involved, so skipping bidiread should reduce some flakiness. I also looked into opentelemetry-go/sdk/metric and the tests look right. I suspect other flakiness is coming from test running too fast that metrics are not collected in time

Fixes #11397

### CODE REVIEW

**Review by danielduhh — APPROVED** [review]

File: storage/integration_test.go [hunk 1]
```diff
@@ -637,6 +637,7 @@ func TestIntegration_DoNotDetectDirectConnectivityWhenDisabled(t *testing.T) {
 
 func TestIntegration_MetricsEnablement(t *testing.T) {
 	ctx := skipHTTP("grpc only test")
+	ctx = skipExtraReadAPIs(ctx, "no reads in test")
 	mr := metric.NewManualReader()
```
Comment (BrennaEpp) [inline storage/integration_test.go:641]: Ah, this guy being out of the multiTransportTest is probably the culprit, but yes we should skip anyway. Thanks Cathy!

**Review by BrennaEpp — APPROVED** [review]
