### PR TITLE
fix(spanner): retry session not found for read

### LINKED ISSUE #2718: spanner: Session not found on Read with KeySet
**Client**

Spanner (v1.7.0)

**Environment**

Cloud Run (fully managed)

**Code**
```go
keySet := spanner.KeySets(
	spanner.Key{ /* ... */ },
	spanner.Key{ /* ... */ },
	spanner.Key{ /* ... */ }
)
err = spannerClient.Single().Read(
	ctx,
	/* ... */,
	keySet,
	/* ... */,
).Do(/* ... */)
```

**Expected behavior**

Request should succeed, and the client handles maintaining the session pool.

**Actual behavior**

Intermittent failure, client returns:
```
code = "NotFound", desc = "Session not found: projects/xxx/instances/xxx/databases/xxx/sessions/AN4G3x93_EfsUJcOlBpnvbOmZELeqImNJjvJv2UiEX5r0rvMzqTU1Juhug7qOA"
```

**Additional context**
Re-running the same request succeeds but sometimes, very seldom, the error is returned.
There are many `Read()` calls being made by our service concurrently in the call-chain, and when the error occurs it is only for one of the calls.

### PR DESCRIPTION
**Pull request by olavloite**
`Session not found` errors were not retried for read operations on a single-use read-only transaction.

Fixes #2718

### CODE REVIEW

File: spanner/transaction.go [hunk 1]
```diff
@@ -133,13 +133,13 @@ func (t *txReadOnly) ReadWithOptions(ctx context.Context, table string, keys Key
...
 	}
-	return stream(
+	return streamWithReplaceSessionFunc(
 		contextWithOutgoingMetadata(ctx, sh.getMetadata()),
 		sh.session.logger,
 		func(ctx context.Context, resumeToken []byte) (streamingReceiver, error) {
 			return client.StreamingRead(ctx,
 				&sppb.ReadRequest{
-					Session:     sid,
+					Session:     t.sh.getID(),
```
Comment (hengfengli) [inline spanner/transaction.go:142]: Should we delete the unused `sid` code above?

Comment (hengfengli) [reply spanner/transaction.go:142]: Shouldn't `t.sh.getID()` and `sid` be same here? So why do we use `t.sh.getID()`?

Comment (olavloite) [reply spanner/transaction.go:142]: Yep, good point. Removed it now.
