### PR TITLE
fix(bigquery): avoid stack overflow on query param with recursive types

### LINKED ISSUE #6884: bigquery: Stack overflow in
**Client**

BigQuery.

**Environment**

macOS M1, `Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64`.

**Go Environment**

Version: `go version go1.19.2 darwin/arm64`.

Environment:

```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/thomas/Library/Caches/go-build"
GOENV="/Users/thomas/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/thomas/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/thomas/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.2/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="$WORK"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lv/qbz3lh7j6gdc43dd1p22bcc40000gn/T/go-build188376126=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Code**

I can't share all code, but the following is pretty close. Note that I'm not sure that passing `[]string` to `RowIterator.Next` is valid, but it's shouldn't overflow it's stack.

```go
package main

func main() {
	query := client.Query("...") // Select a single array of strings.
	rows, err := query.Read(ctx)
	if err != nil {
		return nil, err
	}
	rows.PageInfo().MaxSize = 1 // Only expect a single row.

	var options []string
	if err := rows.Next(&options); err != nil {
		return nil, err
	}

	// Never reached...
}
```

**Expected behavior**

Filled `options` with the array, or at the very least no stack overflow.

**Actual behavior**

Stack overflow. Backtrace: 

<details>

```log
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0x140206403a0 stack=[0x14020640000, 0x14040640000]
fatal error: stack overflow

runtime stack:
runtime.throw({0x10391275e?, 0x1044f3600?})
        /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/panic.go:1047 +0x40 fp=0x16d066d50 sp=0x16d066d20 pc=0x102ee2e20
runtime.newstack()
        /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/stack.go:1103 +0x464 fp=0x16d066f00 sp=0x16d066d50 pc=0x102efd8a4
runtime.morestack()
        /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/asm_arm64.s:316 +0x70 fp=0x16d066f00 sp=0x16d066f00 pc=0x102f14900

goroutine 10 [running]:
runtime.mapaccess2(0x103c379c0, 0x140001bd7d0, 0x14020640408?)
        /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/map.go:456 +0x21c fp=0x140206403a0 sp=0x140206403a0 pc=0x102eba7dc
sync.(*Map).Load(0x14000404a98, {0x103dcb380, 0x103d11ba0})
        /opt/homebrew/Cellar/go/1.19.2/libexec/src/sync/map.go:112 +0xc0 fp=0x14020640420 sp=0x140206403a0 pc=0x102f1e970
cloud.google.com/go/internal/fields.(*Cache).cachedTypeFields(0x14000404a80, {0x103e09b20?, 0x103d11ba0})
        /Users/thomas/go/pkg/mod/cloud.google.com/go@v0.104.0/internal/fields/fields.go:215 +0x64 fp=0x140206404c0 sp=0x14020640420 pc=0x1034460a4
cloud.google.com/go/internal/fields.(*Cache).Fields(0x14020640538?, {0x103e09b20, 0x103d11ba0})
        /Users/thomas/go/pkg/mod/cloud.google.com/go@v0.104.0/internal/fields/fields.go:176 +0x48 fp=0x140206404f0 sp=0x140206404c0 pc=0x103445df8
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:378 +0x5d0 fp=0x140206406d0 sp=0x140206404f0 pc=0x1034653a0
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206408b0 sp=0x140206406d0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020640a90 sp=0x140206408b0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020640c70 sp=0x14020640a90 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020640e50 sp=0x14020640c70 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020641030 sp=0x14020640e50 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020641210 sp=0x14020641030 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206413f0 sp=0x14020641210 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206415d0 sp=0x140206413f0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206417b0 sp=0x140206415d0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020641990 sp=0x140206417b0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020641b70 sp=0x14020641990 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020641d50 sp=0x14020641b70 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020641f30 sp=0x14020641d50 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020642110 sp=0x14020641f30 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206422f0 sp=0x14020642110 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206424d0 sp=0x140206422f0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206426b0 sp=0x140206424d0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020642890 sp=0x140206426b0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020642a70 sp=0x14020642890 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020642c50 sp=0x14020642a70 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020642e30 sp=0x14020642c50 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020643010 sp=0x14020642e30 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206431f0 sp=0x14020643010 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206433d0 sp=0x140206431f0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206435b0 sp=0x140206433d0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020643790 sp=0x140206435b0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020643970 sp=0x14020643790 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020643b50 sp=0x14020643970 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020643d30 sp=0x14020643b50 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020643f10 sp=0x14020643d30 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206440f0 sp=0x14020643f10 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206442d0 sp=0x140206440f0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206444b0 sp=0x140206442d0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020644690 sp=0x140206444b0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020644870 sp=0x14020644690 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020644a50 sp=0x14020644870 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020644c30 sp=0x14020644a50 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020644e10 sp=0x14020644c30 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020644ff0 sp=0x14020644e10 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206451d0 sp=0x14020644ff0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206453b0 sp=0x140206451d0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020645590 sp=0x140206453b0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020645770 sp=0x14020645590 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020645950 sp=0x14020645770 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020645b30 sp=0x14020645950 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020645d10 sp=0x14020645b30 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020645ef0 sp=0x14020645d10 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206460d0 sp=0x14020645ef0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206462b0 sp=0x140206460d0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020646490 sp=0x140206462b0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020646670 sp=0x14020646490 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020646850 sp=0x14020646670 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020646a30 sp=0x14020646850 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020646c10 sp=0x14020646a30 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020646df0 sp=0x14020646c10 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020646fd0 sp=0x14020646df0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206471b0 sp=0x14020646fd0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020647390 sp=0x140206471b0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020647570 sp=0x14020647390 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020647750 sp=0x14020647570 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020647930 sp=0x14020647750 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020647b10 sp=0x14020647930 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020647cf0 sp=0x14020647b10 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020647ed0 sp=0x14020647cf0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x140206480b0 sp=0x14020647ed0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020648290 sp=0x140206480b0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020648470 sp=0x14020648290 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020648650 sp=0x14020648470 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020648830 sp=0x14020648650 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020648a10 sp=0x14020648830 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020648bf0 sp=0x14020648a10 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020648dd0 sp=0x14020648bf0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020648fb0 sp=0x14020648dd0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020649190 sp=0x14020648fb0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020649370 sp=0x14020649190 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020649550 sp=0x14020649370 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020649730 sp=0x14020649550 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020649910 sp=0x14020649730 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020649af0 sp=0x14020649910 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020649cd0 sp=0x14020649af0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x14020649eb0 sp=0x14020649cd0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064a090 sp=0x14020649eb0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064a270 sp=0x1402064a090 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064a450 sp=0x1402064a270 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064a630 sp=0x1402064a450 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064a810 sp=0x1402064a630 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064a9f0 sp=0x1402064a810 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064abd0 sp=0x1402064a9f0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064adb0 sp=0x1402064abd0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064af90 sp=0x1402064adb0 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064b170 sp=0x1402064af90 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064b350 sp=0x1402064b170 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064b530 sp=0x1402064b350 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064b710 sp=0x1402064b530 pc=0x103465768
cloud.google.com/go/bigquery.paramType({0x103e09b20, 0x103c54160}, {0x103d4ea60?, 0x1400018ebe0?, 0x0?})
        /Users/thomas/go/pkg/mod/cloud.google.com/go/bigquery@v1.42.0/params.go:383 +0x998 fp=0x1402064b8f0 sp=0x1402064b710 pc=0x103465768
...additional frames elided...
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/thomas/go/pkg/mod/google.golang.org/grpc@v1.50.0/server.go:953 +0x290
```

</details>

**Additional context**

Related code is: https://github.com/googleapis/google-cloud-go/blob/92243e770489f11cbd79d28240b4e7f0b23d3061/bigquery/params.go#L383

### PR DESCRIPTION
**Pull request by alvarowolfx**
Resolves #6884

### CODE REVIEW

File: bigquery/params.go [hunk 1]
```diff
@@ -380,6 +381,12 @@ func paramType(t reflect.Type, v reflect.Value) (*bq.QueryParameterType, error)
 			return nil, err
 		}
 		for _, f := range fields {
+			prefixes := []string{"*", "[]"} // check pointer and arrays
+			for _, prefix := range prefixes {
+				if strings.TrimPrefix(t.String(), prefix) == strings.TrimPrefix(f.Type.String(), prefix) {
+					return nil, fmt.Errorf("bigquery: Go type %s cannot be represented as a parameter due to a cycle detected", t)
```
Comment (shollyman) [inline bigquery/params.go:387]: Do we want to be clearer that this is a recursive type problem?  I worry that only mentioning a cycle is insufficient?

**Review by shollyman — APPROVED** [review]
