### PR TITLE
fix(spanner): do not export metrics during shutdown if prev export was less than 30 seconds ago

### LINKED ISSUE #12017: spanner: Close causes /google.monitoring.v3.MetricService/CreateServiceTimeSeries error internally
## Client

Spanner

## Environment

Alpine Docker on GKE
Go version: 1.24

## Code and Dependencies

```go
package main

import (
	"context"
	"flag"
	"log"
	"time"

	"cloud.google.com/go/spanner"
	"google.golang.org/api/option"
	"google.golang.org/grpc"
)

var db string

func init() {
	flag.StringVar(&db, "db", "", "db uri.")
}
func main() {
	flag.Parse()
	ctx := context.Background()
	cli, err := spanner.NewClientWithConfig(
		ctx,
		db,
		spanner.ClientConfig{SessionPoolConfig: spanner.DefaultSessionPoolConfig, DisableRouteToLeader: false},
		option.WithGRPCDialOption(grpc.WithUnaryInterceptor(uinterceptor)),
		option.WithGRPCDialOption(grpc.WithStreamInterceptor(sinterceptor)),
	)
	if err != nil {
		log.Fatal(err)
	}
	go func(ctx context.Context, cli *spanner.Client) {
		for {
			select {
			case <-ctx.Done():
				break
			default:
				singerColumns := []string{"SingerId", "FirstName", "LastName"}
				m := []*spanner.Mutation{
					spanner.InsertOrUpdate("Singers", singerColumns, []interface{}{"a", "Melissa", "Garcia"}),
				}
				_, err := cli.Apply(ctx, m)
				if err != nil {
					log.Printf("apply failed. %v\n", err)
				}
				time.Sleep(10 * time.Second)
			}
		}
	}(ctx, cli)
	time.Sleep(1*time.Minute + 1*time.Second)
	log.Print("call Close.\n")
	cli.Close()
	time.Sleep(5 * time.Second)
}

func uinterceptor(
	ctx context.Context,
	method string,
	req, reply interface{},
	cc *grpc.ClientConn,
	invoker grpc.UnaryInvoker,
	opts ...grpc.CallOption,
) error {
	log.Printf("intercept unary %s\n", method)
	err := invoker(ctx, method, req, reply, cc, opts...)
	if err != nil && method == "/google.monitoring.v3.MetricService/CreateServiceTimeSeries" {
		log.Printf("error occuerd. %v\n", err)
	}
	return err
}

func sinterceptor(ctx context.Context, desc *grpc.StreamDesc, cc *grpc.ClientConn, method string, streamer grpc.Streamer, opts ...grpc.CallOption) (grpc.ClientStream, error) {
	log.Printf("intercept stream:%s\n", method)
	s, err := streamer(ctx, desc, cc, method, opts...)
	if err != nil {
		return nil, err
	}
	return &wrappedStream{s, method}, nil
}

type wrappedStream struct {
	grpc.ClientStream

	method string
}

func (w *wrappedStream) RecvMsg(m interface{}) error {
	log.Printf("RecvMsg:%s\n", w.method)
	return w.ClientStream.RecvMsg(m)
}
func (w *wrappedStream) SendMsg(m interface{}) error {
	log.Printf("SendMsg:%s\n", w.method)
	return w.ClientStream.SendMsg(m)
}
```

<details>
  <summary>go.mod</summary>

```text
module github.com/nktks/test/spanbuiltinmetrics

go 1.24.1

require cloud.google.com/go/spanner v1.79.0

require (
	cel.dev/expr v0.19.2 // indirect
	cloud.google.com/go v0.120.0 // indirect
	cloud.google.com/go/auth v0.15.0 // indirect
	cloud.google.com/go/auth/oauth2adapt v0.2.7 // indirect
	cloud.google.com/go/compute/metadata v0.6.0 // indirect
	cloud.google.com/go/monitoring v1.24.1 // indirect
	github.com/GoogleCloudPlatform/grpc-gcp-go/grpcgcp v1.5.2 // indirect
	github.com/GoogleCloudPlatform/opentelemetry-operations-go/detectors/gcp v1.27.0 // indirect
	github.com/cespare/xxhash/v2 v2.3.0 // indirect
	github.com/cncf/xds/go v0.0.0-20250121191232-2f005788dc42 // indirect
	github.com/envoyproxy/go-control-plane/envoy v1.32.4 // indirect
	github.com/envoyproxy/protoc-gen-validate v1.2.1 // indirect
	github.com/felixge/httpsnoop v1.0.4 // indirect
	github.com/go-logr/logr v1.4.2 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
	github.com/google/s2a-go v0.1.9 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/googleapis/enterprise-certificate-proxy v0.3.6 // indirect
	github.com/googleapis/gax-go/v2 v2.14.1 // indirect
	github.com/planetscale/vtprotobuf v0.6.1-0.20240319094008-0393e58bdf10 // indirect
	go.opencensus.io v0.24.0 // indirect
	go.opentelemetry.io/auto/sdk v1.1.0 // indirect
	go.opentelemetry.io/contrib/detectors/gcp v1.35.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.59.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.59.0 // indirect
	go.opentelemetry.io/otel v1.35.0 // indirect
	go.opentelemetry.io/otel/metric v1.35.0 // indirect
	go.opentelemetry.io/otel/sdk v1.35.0 // indirect
	go.opentelemetry.io/otel/sdk/metric v1.35.0 // indirect
	go.opentelemetry.io/otel/trace v1.35.0 // indirect
	golang.org/x/crypto v0.36.0 // indirect
	golang.org/x/net v0.37.0 // indirect
	golang.org/x/oauth2 v0.28.0 // indirect
	golang.org/x/sync v0.12.0 // indirect
	golang.org/x/sys v0.31.0 // indirect
	golang.org/x/text v0.23.0 // indirect
	golang.org/x/time v0.11.0 // indirect
	google.golang.org/api v0.227.0 // indirect
	google.golang.org/genproto v0.0.0-20250303144028-a0af3efb3deb // indirect
	google.golang.org/genproto/googleapis/api v0.0.0-20250313205543-e70fdf4c4cb4 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20250313205543-e70fdf4c4cb4 // indirect
	google.golang.org/grpc v1.71.0 // indirect
	google.golang.org/protobuf v1.36.6 // indirect
)
```

</details>

<details><summary>Execute result (Click me)</summary>

```
> go run main.go -db "projects/${PROJECT}/instances/${INSTANCE}/databases/${DATABASE}"
2025/04/20 21:35:55 intercept unary /google.spanner.v1.Spanner/BatchCreateSessions
2025/04/20 21:35:55 intercept unary /google.spanner.v1.Spanner/BatchCreateSessions
2025/04/20 21:35:55 intercept unary /google.spanner.v1.Spanner/BatchCreateSessions
2025/04/20 21:35:55 intercept unary /google.spanner.v1.Spanner/BatchCreateSessions
2025/04/20 21:35:56 intercept unary /google.spanner.v1.Spanner/BeginTransaction
2025/04/20 21:35:56 intercept unary /google.spanner.v1.Spanner/Commit
2025/04/20 21:36:06 intercept unary /google.spanner.v1.Spanner/BeginTransaction
2025/04/20 21:36:06 intercept unary /google.spanner.v1.Spanner/Commit
2025/04/20 21:36:16 intercept unary /google.spanner.v1.Spanner/BeginTransaction
2025/04/20 21:36:16 intercept unary /google.spanner.v1.Spanner/Commit
2025/04/20 21:36:26 intercept unary /google.spanner.v1.Spanner/BeginTransaction
2025/04/20 21:36:26 intercept unary /google.spanner.v1.Spanner/Commit
2025/04/20 21:36:36 intercept unary /google.spanner.v1.Spanner/BeginTransaction
2025/04/20 21:36:36 intercept unary /google.spanner.v1.Spanner/Commit
2025/04/20 21:36:46 intercept unary /google.spanner.v1.Spanner/BeginTransaction
2025/04/20 21:36:46 intercept unary /google.spanner.v1.Spanner/Commit
2025/04/20 21:36:55 intercept unary /google.monitoring.v3.MetricService/CreateServiceTimeSeries
2025/04/20 21:36:56 call Close.
2025/04/20 21:36:56 intercept unary /google.monitoring.v3.MetricService/CreateServiceTimeSeries
2025/04/20 21:36:56 intercept unary /google.spanner.v1.Spanner/BeginTransaction
2025/04/20 21:36:56 intercept unary /google.spanner.v1.Spanner/Commit
2025/04/20 21:36:56 error occuerd. rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: timeSeries[0-11]: write for resource=spanner_instance_client{location:global,instance_id:xxxx,client_hash:00011c,instance_config:unknown} failed with: One or more points were written more frequently than the maximum sampling period configured for the metric.
2025/04/20 21:36:56 intercept unary /google.monitoring.v3.MetricService/CreateServiceTimeSeries
2025/04/20 21:36:57 error occuerd. rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: timeSeries[0-11]: write for resource=spanner_instance_client{location:global,client_hash:00011c,instance_id:xxxx,instance_config:unknown} failed with: One or more points were written more frequently than the maximum sampling period configured for the metric.
```

</details>

## Expected behavior

- No error happens when we call `Close`.
- Pending telemetry is exported even during `Close`.

## Actual behavior

- If we intercept gRPC rpc calls, error shown as above `Code and Dependencies`.
- Some builtin metrics aren't exported to Cloud Monitoring.

## Additional context

- This issue is due to `go.opentelemetry.io/otel/sdk/metric.(*PeriodicReader)` side implementation.
  -  Cloud Monitoring has some quota like `Rate at which data can be written to a single time series`, `one point each 5 seconds`.
  - https://cloud.google.com/monitoring/quotas#custom_metrics_quotas
  - (But I'm not sure error message in `Execute result` is related to this quota)
  - `*PeriodicReader.Shutdown` and `*PeriodicReader.ForceFlush` called at [here](https://github.com/googleapis/google-cloud-go/blob/spanner/v1.78.0/spanner/metrics.go#L245-L246) forces export pending metrics, so it hits above quotas.
  - I created otel side issue to wait some seconds in `Shutdown`. https://github.com/open-telemetry/opentelemetry-go/issues/6677
    - But they said https://github.com/open-telemetry/opentelemetry-go/issues/6677#issuecomment-2817228311
- [The export on the Spanner side](https://github.com/googleapis/google-cloud-go/blob/spanner/v1.79.0/spanner/metrics.go#L245-L246) also needs to be modified.
  - It calls both `ForceFlush` and `Shutdown`, both methods force export pending metrics. [ref](https://github.com/open-telemetry/opentelemetry-go/blob/sdk/metric/v1.35.0/sdk/metric/periodic_reader.go#L275-L347)
  - After otel side issue is fixed, I think we only need to call `Shutdown` to shut down and export pending metrics.

### LINKED ISSUE #12091: spanner: Client library exceeding google.monitoring.v3.MetricService.CreateServiceTimeSeries limits
## Client

Using cloud.google.com/go/spanner v1.73.0.

## Environment

GKE, go 1.23.8

## Code and Dependencies

We run a go web server which makes calls back to Cloud Spanner using the client library.

Our application performs around 5-12 kQPS (i.e. 5000-12000 QPS) of the StreamingRead and 1-4k QPS of the other RPCs on our production deployment. This load originates over many docker containers (i.e. many instances of the client library).

## Expected behavior

No errors logged to Cloud Logging.

## Actual behavior

We receive many errors (around 10-30 per second), similar to:
`
One or more TimeSeries could not be written: timeSeries[0-23] (example metric.type="spanner.googleapis.com/internal/client/operation_latencies", metric.labels={"client_uid": "<omitted>", "directpath_used": "false", "directpath_enabled": "false", "database": "<omitted>", "status": "OK", "method": "Spanner.ExecuteStreamingSql", "client_name": "spanner-go/1.73.0"}): write for resource=spanner_instance_client{instance_config:unknown,client_hash:000171,instance_id:prod,location:us-central1} failed with: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: spanner.googleapis.com/internal/client/operation_latencies, Timestamps: {Youngest Existing: '2025/04/30-18:56:30.964', New: '2025/04/30-18:57:00.232'}}
`

Referencing methods:
- Spanner.ExecuteStreamingSql
- Spanner.StreamingRead
- Spanner.BeginTransaction
- and others.

And metrics:
- spanner.googleapis.com/internal/client/operation_count
- spanner.googleapis.com/internal/client/operation_latencies
- spanner.googleapis.com/internal/client/attempt_latencies

## Additional context

This error has been occuring for at least 30 days, but we did not have it in the past. I have not gone back to investigate which client library version introduced it.

My Google LDAP is meiring@.

### PR DESCRIPTION
**Pull request by sakthivelmanii**
Fixes #12017 
Fixes #12091

### CODE REVIEW

File: spanner/metrics_monitoring_exporter.go [hunk 1]
```diff
@@ -107,11 +109,19 @@ func newMonitoringExporter(ctx context.Context, project, compression string, cli
...
+		lastExportedAt:   time.Now().Add(-time.Minute),
 		client:           client,
 		shutdown:         make(chan struct{}),
 	}, nil
 }
 
+func (me *monitoringExporter) close() {
+	// stop the exporter if last export happens within half-time of default sample period
+	if time.Since(me.lastExportedAt) <= (defaultSamplePeriod / 2) {
+		me.stop = true
```
Comment (olavloite) [inline spanner/metrics_monitoring_exporter.go:121]: Does this field need to be protected by a mutex? That is; could it be that there are two different goroutines that call `close()` and `Export()` at the same time?

File: spanner/metrics_monitoring_exporter.go [hunk 2]
```diff
@@ -96,6 +96,8 @@ type monitoringExporter struct {
 	shutdown         chan struct{}
 	client           *monitoring.MetricClient
 	shutdownOnce     sync.Once
+	stop             bool
```
Comment (rahul2393) [inline spanner/metrics_monitoring_exporter.go:99]: It is always best practice to acquire the lock before changing attributes of a struct when fields can be accessed/modified from more than 1 threads

**Review by olavloite — COMMENTED** [review]
I think that a better title for this PR would be:

`do not export metrics during shutdown if prev export was less than 30 seconds ago`

**Review by rahul2393 — CHANGES_REQUESTED** [review]

File: spanner/metrics_monitoring_exporter.go [hunk 3]
```diff
@@ -178,6 +191,7 @@ func (me *monitoringExporter) exportTimeSeries(ctx context.Context, rm *otelmetr
 		errs = append(errs, err)
 	}
 
+	me.lastExportedAt = time.Now()
```
[the remark this answers is not in the document]
Comment (sakthivelmanii) [reply spanner/metrics_monitoring_exporter.go:194]: Exporter have one goroutine which triggers for every 60 seconds. So I feel it's not required. We will not have any scenario where multiple exports happens in parallel.

File: spanner/metrics_monitoring_exporter.go (hunk 2 above)
Comment (sakthivelmanii) [reply spanner/metrics_monitoring_exporter.go:99]: In this case, this field can't be modified by multiple threads since we are calling it right? Do you see any possibility that it can be called by multiple threads?

File: spanner/metrics_monitoring_exporter.go [hunk 4]
```diff
@@ -107,11 +109,19 @@ func newMonitoringExporter(ctx context.Context, project, compression string, cli
 		projectID:        project,
 		compression:      compression,
 		clientAttributes: clientAttributes,
+		lastExportedAt:   time.Now().Add(-time.Minute),
 		client:           client,
 		shutdown:         make(chan struct{}),
 	}, nil
 }
 
+func (me *monitoringExporter) close() {
```
[the remark this answers is not in the document]
Comment (sakthivelmanii) [reply spanner/metrics_monitoring_exporter.go]: done

File: spanner/metrics_monitoring_exporter.go (hunk 1 above)
Comment (sakthivelmanii) [reply spanner/metrics_monitoring_exporter.go]: Done

Comment (sakthivelmanii) [reply spanner/metrics_monitoring_exporter.go]: It's not possible. close() and Export() can be called in parallel. Export() doesn't change stop value. Two goroutines can't modify the same field.

File: spanner/metrics_monitoring_exporter.go [hunk 5]
```diff
@@ -107,11 +110,21 @@ func newMonitoringExporter(ctx context.Context, project, compression string, cli
...
+		lastExportedAt:   time.Now().Add(-time.Minute),
 		client:           client,
 		shutdown:         make(chan struct{}),
 	}, nil
 }
 
+func (me *monitoringExporter) stop() {
+	// stop the exporter if last export happens within half-time of default sample period
+	if time.Since(me.lastExportedAt) <= (defaultSamplePeriod / 2) {
+		me.mu.Lock()
```
Comment (rahul2393) [inline spanner/metrics_monitoring_exporter.go:122]: lock should be acquired before checking lastExportedAT

File: spanner/metrics_monitoring_exporter.go [hunk 6]
```diff
@@ -367,7 +386,7 @@ func histToDistribution[N int64 | float64](hist otelmetricdata.HistogramDataPoin
 }
 
 func numberDataPointToValue[N int64 | float64](
-	point otelmetricdata.DataPoint[N],
```
Comment (rahul2393) [inline spanner/metrics_monitoring_exporter.go:370]: is this change expected?

File: spanner/metrics_monitoring_exporter.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (olavloite) [reply spanner/metrics_monitoring_exporter.go:198]: That is true, but that is not what I'm worried about. `lastExportedAt` is written by this method, which is called by the goroutine handling exports. The field is read by the `stop()` method, which is called by any application goroutine that closes the Spanner client. Meaning that you could have one goroutine reading the value while another is writing the value.

See https://go.dev/doc/articles/race_detector#Introduction

File: spanner/metrics_monitoring_exporter.go (hunk 6 above)
Comment (sakthivelmanii) [reply spanner/metrics_monitoring_exporter.go:370]: it's automatically formatting this.

File: spanner/benchmarks/benchmarks.go [hunk 7]
```diff
@@ -386,7 +386,7 @@ func parseCloudEnvironment(environment string) cloudEnvironment {
 }
 
 func percentiles(percentile float32, latencies []int64) any {
-	rank := (percentile * float32(len(latencies)-1)) + 1
+	rank := percentile * float32(len(latencies)-1)
```
Comment (olavloite) [inline spanner/benchmarks/benchmarks.go:389]: Is this intentional?

File: spanner/metrics_monitoring_exporter.go [hunk 8]
```diff
@@ -107,11 +110,21 @@ func newMonitoringExporter(ctx context.Context, project, compression string, cli
...
 		clientAttributes: clientAttributes,
+		lastExportedAt:   time.Now().Add(-time.Minute),
 		client:           client,
 		shutdown:         make(chan struct{}),
 	}, nil
 }
 
+func (me *monitoringExporter) stop() {
+	// stop the exporter if last export happens within half-time of default sample period
+	me.mu.Lock()
```
Comment (olavloite) [inline spanner/metrics_monitoring_exporter.go:121]: super nit: it is idiomatic to use `defer me.mu.Unlock()` here

File: spanner/metrics_monitoring_exporter.go [hunk 9]
```diff
@@ -96,6 +96,9 @@ type monitoringExporter struct {
 	shutdown         chan struct{}
 	client           *monitoring.MetricClient
 	shutdownOnce     sync.Once
+	mu               sync.Mutex
```
Comment (olavloite) [inline spanner/metrics_monitoring_exporter.go:99]: nit: Add an empty line here. It is common to create a separate 'group' for the fields that are protected by a mutex. So you get this:

```
type monitoringExporter struct {
  ...
  shutdownOnce sync.Once
  
  mu sync.Mutex
  stopExport bool
  lastExportedAt time.Time
}
```

**Review by olavloite — APPROVED** [review]

File: spanner/benchmarks/benchmarks.go (hunk 7 above)
Comment (sakthivelmanii) [reply spanner/benchmarks/benchmarks.go]: Removed it

File: spanner/metrics_monitoring_exporter.go (hunk 8 above)
Comment (sakthivelmanii) [reply spanner/metrics_monitoring_exporter.go:122]: Done

File: spanner/metrics_monitoring_exporter.go (hunk 9 above)
Comment (sakthivelmanii) [reply spanner/metrics_monitoring_exporter.go]: Done

**Review by rahul2393 — APPROVED** [review]
