### PR TITLE
test(spanner): update max staleness bound value

### LINKED ISSUE #10084: spanner: TestIntegration_SingleUse failed
Note: #7763 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 5a8c88956ea11eaf3e8aa8cffadfca06bf58c51d
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/6301ed02-55cd-47f5-ad5f-f335a6e8380f), [Sponge](http://sponge2/6301ed02-55cd-47f5-ad5f-f335a6e8380f)
status: failed

### PR DESCRIPTION
**Pull request by harshachinta**
`TestIntegration_SingleUse/max_staleness` is showing flaky behavior and this PR fixes it.

**Background**: The current test has a Max staleness value of `1 sec`. This Bounded staleness mode allow Spanner to pick the read timestamp, subject to a user- provided staleness bound. Spanner chooses the newest timestamp within the provided staleness bound. More details `[here](https://cloud.google.com/spanner/docs/timestamp-bounds#bounded_staleness)`.

**Flakiness Reason**: The test verifies whether the chosen read timestamp is after writes[3] timestamp. But since the staleness value is 1 sec, the chosen timestamp by spanner can be much before the writes[3] timestamp which gices a flaky behaviour with below error
```
SingleUse.Query doesn't return expected timestamp: read got timestamp 2024-05-02 07:02:58.245414 +0000 UTC, want it to be no earlier than 2024-05-02 07:02:58.289881 +0000 UTC
```

Choosing a lower value of staleness ensures that the chosen timestamp is always above the writes[3] timestamp.

Fixes #10084

### CODE REVIEW

File: spanner/integration_test.go [hunk 1]
```diff
@@ -623,7 +623,7 @@ func TestIntegration_SingleUse(t *testing.T) {
 		{
 			name: "max_staleness",
 			want: [][]interface{}{{int64(1), "Marc", "Foo"}, {int64(3), "Alpha", "Beta"}, {int64(4), "Last", "End"}},
-			tb:   MaxStaleness(time.Second),
+			tb:   MaxStaleness(time.Nanosecond),
```
Comment (rahul2393) [inline spanner/integration_test.go:626]:
```suggestion
			tb:   MaxStaleness(time.Second),
```

File: spanner/integration_test.go [hunk 2]
```diff
@@ -623,7 +623,7 @@ func TestIntegration_SingleUse(t *testing.T) {
...
 			checkTs: func(ts time.Time) error {
 				if ts.Before(writes[3].ts) {
```
Comment (rahul2393) [inline spanner/integration_test.go:628]:
```suggestion
				if writes[3].ts.Sub(ts) < time.Second {
```

Comment (rahul2393) [reply spanner/integration_test.go:628]: Can we do this, instead of reducing the max staleness, so that the check is more undertandable?

**Review by rahul2393 — COMMENTED** [review]
Can we do this, instead of reducing the max staleness, so that the check is more undertandable?

File: spanner/integration_test.go (hunk 2 above)
Comment (harshachinta) [reply spanner/integration_test.go:628]: This case will always fail because the difference between 2 timestamps will always be less than 1 sec

Comment (rahul2393) [reply spanner/integration_test.go:628]: Updated

**Review by rahul2393 — APPROVED** [review]
