### PR TITLE
fix(spanner): mark SessionPoolConfig.MaxBurst deprecated

### LINKED ISSUE #4089: spanner: mark SessionPoolConfig.MaxBurst as unused
SessionPoolConfig.MaxBurst doesn't seem to be used from this change.
https://github.com/googleapis/google-cloud-go/commit/53898305c6f21b3c3eef34fcff6c61a2cb36f602

To avoid confusion, it should be documented as unused.
(I think it is not deleted because of breaking changes)

### PR DESCRIPTION
**Pull request by hengfengli**
Fixes #4089

### CODE REVIEW

**Comment by hengfengli** [comment]
@olavloite Can we remove the related test if we deprecate `SessionPoolConfig.MaxBurst`? It seems the test still passes.

File: spanner/session.go [hunk 1]
```diff
@@ -409,7 +409,8 @@ type SessionPoolConfig struct {
 	// Defaults to 0.
 	MaxIdle uint64
 
-	// MaxBurst is the maximum number of concurrent session creation requests.
+	// (Deprecated) MaxBurst is the maximum number of concurrent session
+	// creation requests.
```
Comment (codyoss) [inline spanner/session.go:413]: nit: Could you format this deprecation notice in this form: https://github.com/golang/go/wiki/Deprecated#examples

This way linters will pick it up in developers code and issue a warning. Also, is there something people should migrate to instead?

Comment (hengfengli) [reply spanner/session.go:413]: Thanks for the link. Will do. 

@olavloite Do we still support MaxBurst? or something they can migrate to?

Comment (hengfengli) [reply spanner/session.go:413]: From my understanding, the sessions will be created in a batch and the size of the batch (max burst) is decided by `SessionPoolConfig.incStep`. However, `SessionPoolConfig.incStep` is not configurable.

Comment (olavloite) [reply spanner/session.go:413]: We do not support `MaxBurst` anymore, and there is also nothing that replaces it. `SessionPool.incStep` will determine the number of sessions that is created in each `BatchCreateSessions` RPC invocation, and is not (externally) configurable, as the default value has been shown to be a reasonable configuration for all tested scenarios. Also, `SessionPool.incStep` is different from `MaxBurst`. `MaxBurst` was used to __limit__ the number of sessions that the session pool could create within a time frame. This was an early safety valve to prevent a client from overwhelming the backend if a large number of sessions was suddenly needed. The session pool would then pause the creation of sessions for a while. Such a pause is no longer needed and the implementation has been removed from the pool.

**Review by olavloite — APPROVED** [review]

**Comment by hengfengli** [comment]
@olavloite Thanks for the explanation. Please take a look at the latest change again (I put your explanation into the comment).

**Review by olavloite — APPROVED** [review]
