### PR TITLE
test(storage): improve object cleanup

### LINKED ISSUE #8259: storage: TestIntegration_Copy failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 22a908b0bd26f131c6033ec3fc48eaa2d2cd0c0e
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/0dbf8670-16d9-4e30-8d3b-c094fc98a0ba), [Sponge](http://sponge2/0dbf8670-16d9-4e30-8d3b-c094fc98a0ba)
status: failed
<details><summary>Test output</summary><br><pre>    integration_test.go:1692: copyObj.Delete: googleapi: Error 504: Deadline=9.873s, gatewayTimeout</pre></details>

### PR DESCRIPTION
**Pull request by tritone**
Use the test helper mustDeleteObject function and make it resilient to transient failures. Also switch to using t.Helper and t.Cleanup when possible for test helper funcs.

We should probably move other tests to do this at some point; could be a small fixit project.

Fixes #8259

### CODE REVIEW

File: storage/integration_test.go [hunk 1]
```diff
@@ -272,7 +272,9 @@ func multiTransportTest(ctx context.Context, t *testing.T,
 	opts ...option.ClientOption) {
 	for transport, client := range initTransportClients(ctx, t, opts...) {
 		t.Run(transport, func(t *testing.T) {
-			defer client.Close()
+			t.Cleanup(func() {
+				client.Close()
```
Comment (BrennaEpp) [inline storage/integration_test.go:276]: Nice!

**Review by BrennaEpp — APPROVED** [review]

File: storage/integration_test.go (hunk 1 above)
Comment (tritone) [reply storage/integration_test.go:276]: Yes, turns out this is necessary b/c defer calls run before t.Cleanup calls :)

File: storage/integration_test.go [hunk 2]
```diff
@@ -5196,7 +5199,14 @@ func (h testHelper) mustObjectAttrs(o *ObjectHandle) *ObjectAttrs {
...
-	if err := o.Delete(context.Background()); err != nil {
+	if err := o.Retryer(WithPolicy(RetryAlways)).Delete(context.Background()); err != nil {
+		var apiErr *apierror.APIError
+		if ok := errors.As(err, &apiErr); ok {
+			// Object may already be deleted with retry; if so skip.
+			if apiErr.HTTPCode() == 404 || apiErr.GRPCStatus().Code() == codes.NotFound {
+				return
+			}
+		}
 		h.t.Fatalf("%s: delete object %s from bucket %s: %v", loc(), o.ObjectName(), o.BucketName(), err)
```
[the remark this answers is not in the document]
Comment (tritone) [reply storage/integration_test.go]: Went ahead and just did this and got rid of loc()
