### PR TITLE
fix(bigquery): bq connection auth scopes

### LINKED ISSUE #6744: bigquery: TestIntegration_RoutineRemoteUDF failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: d9a437de75a5f5151cd000d8f9a6b7fc567d8551
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/d9d2d7a5-dfb8-4766-b17d-bfae3256aeec), [Sponge](http://sponge2/d9d2d7a5-dfb8-4766-b17d-bfae3256aeec)
status: failed
<details><summary>Test output</summary><br><pre>    routine_integration_test.go:106: rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes.
        error details: name = ErrorInfo reason = ACCESS_TOKEN_SCOPE_INSUFFICIENT domain = googleapis.com metadata = map[method:google.cloud.bigquery.connection.v1.ConnectionService.CreateConnection service:bigqueryconnection.googleapis.com]</pre></details>

### PR DESCRIPTION
**Pull request by alvarowolfx**
Resolves #6744

### CODE REVIEW

File: bigquery/integration_test.go [hunk 1]
```diff
@@ -158,6 +158,7 @@ func initIntegrationTest() func() {
 		bqOpts := []option.ClientOption{option.WithTokenSource(ts)}
 		sOpts := []option.ClientOption{option.WithTokenSource(testutil.TokenSource(ctx, storage.ScopeFullControl))}
 		ptmOpts := []option.ClientOption{option.WithTokenSource(testutil.TokenSource(ctx, "https://www.googleapis.com/auth/cloud-platform"))}
+		connOpts := []option.ClientOption{option.WithTokenSource(testutil.TokenSource(ctx, connection.DefaultAuthScopes()...))}
```
Comment (shollyman) [inline bigquery/integration_test.go:161]: Maybe we just use the cloud platform scope directly here as well??  The default is bigquery + cloud platform, but cloud-platform already contains bigquery.

Comment (alvarowolfx) [reply bigquery/integration_test.go:161]: I wonder if this is an error on the `connection.DefaultAuthScopes` method, as it returns both scopes. For me is easier to understand the code by using that method instead of putting a scope directly, but you're right, the cloud-platform scope would cover what is needed.

**Review by shollyman — APPROVED** [review]
