### PR TITLE
fix(bttest): fix race condition in SampleRowKeys

### LINKED ISSUE #2600: bigtable: emulator crashes with concurrent operations
We never filed a bug for this, though we had plenty of communication with the emulator developers in googleapis/google-cloud-cpp#441.

The emulator crashes when performing concurrent operations. I think maybe SampleRowKeys combined with DropRowRange.

The first uses a lock to prevent problems:

https://github.com/googleapis/google-cloud-go/blob/fb3791807bf818c5c9d78d2c7e84303192d62de6/bigtable/bttest/inmem.go#L1064

The second does not seem to use the same lock:

https://github.com/googleapis/google-cloud-go/blob/fb3791807bf818c5c9d78d2c7e84303192d62de6/bigtable/bttest/inmem.go#L252-L287

That seems racy.

### PR DESCRIPTION
**Pull request by coryan**
Fixes #2600.

After this change running `go test -race .` passes cleanly. Before this change running with `go test -race` I got:

```
==================
WARNING: DATA RACE
Write at 0x00c001112b98 by goroutine 243:
  cloud.google.com/go/bigtable/bttest.(*server).DropRowRange()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:264 +0x7b1
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func3()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:331 +0x14c

Previous read at 0x00c001112b98 by goroutine 237:
  cloud.google.com/go/bigtable/bttest.(*table).mutableRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:1222 +0x21d
  cloud.google.com/go/bigtable/bttest.(*server).MutateRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:795 +0x1bd
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func1()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:307 +0x564
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func2()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:316 +0x51

Goroutine 243 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:325 +0x664
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202

Goroutine 237 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:315 +0x5f0
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202
==================
==================
WARNING: DATA RACE
Read at 0x00c000517810 by goroutine 237:
  github.com/google/btree.(*BTree).Get()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:819 +0x248
  cloud.google.com/go/bigtable/bttest.(*table).mutableRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:1222 +0x20d
  cloud.google.com/go/bigtable/bttest.(*server).MutateRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:795 +0x1bd
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func1()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:307 +0x564
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func2()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:316 +0x51

Previous write at 0x00c000517810 by goroutine 243:
  github.com/google/btree.NewWithFreeList()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:136 +0x6e4
  github.com/google/btree.New()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:128 +0x6b6
  cloud.google.com/go/bigtable/bttest.(*server).DropRowRange()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:264 +0x793
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func3()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:331 +0x14c

Goroutine 237 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:315 +0x5f0
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202

Goroutine 243 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:325 +0x664
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202
==================
==================
WARNING: DATA RACE
Read at 0x00c000517fd0 by goroutine 237:
  github.com/google/btree.(*BTree).ReplaceOrInsert()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:687 +0x74
  cloud.google.com/go/bigtable/bttest.(*table).mutableRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:1227 +0x3c4
  cloud.google.com/go/bigtable/bttest.(*server).MutateRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:795 +0x1bd
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func1()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:307 +0x564
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func2()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:316 +0x51

Previous write at 0x00c000517fd0 by goroutine 243:
  github.com/google/btree.NewWithFreeList()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:136 +0x6e4
  github.com/google/btree.New()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:128 +0x6b6
  cloud.google.com/go/bigtable/bttest.(*server).DropRowRange()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:264 +0x793
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func3()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:331 +0x14c

Goroutine 237 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:315 +0x5f0
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202

Goroutine 243 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:325 +0x664
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202
==================
==================
WARNING: DATA RACE
Read at 0x00c000517fd8 by goroutine 237:
  github.com/google/btree.(*BTree).ReplaceOrInsert()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:688 +0x7bd
  cloud.google.com/go/bigtable/bttest.(*table).mutableRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:1227 +0x3c4
  cloud.google.com/go/bigtable/bttest.(*server).MutateRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:795 +0x1bd
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func1()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:307 +0x564
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func2()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:316 +0x51

Previous write at 0x00c000517fd8 by goroutine 243:
  github.com/google/btree.NewWithFreeList()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:136 +0x6e4
  github.com/google/btree.New()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:128 +0x6b6
  cloud.google.com/go/bigtable/bttest.(*server).DropRowRange()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:264 +0x793
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func3()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:331 +0x14c

Goroutine 237 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:315 +0x5f0
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202

Goroutine 243 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:325 +0x664
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202
==================
==================
WARNING: DATA RACE
Read at 0x00c00050e3b0 by goroutine 237:
  github.com/google/btree.(*copyOnWriteContext).newNode()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:646 +0x7dc
  github.com/google/btree.(*BTree).ReplaceOrInsert()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:688 +0x7b1
  cloud.google.com/go/bigtable/bttest.(*table).mutableRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:1227 +0x3c4
  cloud.google.com/go/bigtable/bttest.(*server).MutateRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:795 +0x1bd
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func1()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:307 +0x564
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func2()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:316 +0x51

Previous write at 0x00c00050e3b0 by goroutine 243:
  github.com/google/btree.NewWithFreeList()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:138 +0x747
  github.com/google/btree.New()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:128 +0x6b6
  cloud.google.com/go/bigtable/bttest.(*server).DropRowRange()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:264 +0x793
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func3()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:331 +0x14c

Goroutine 237 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:315 +0x5f0
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202

Goroutine 243 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:325 +0x664
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202
==================
==================
WARNING: DATA RACE
Write at 0x00c000517fa0 by goroutine 237:
  sync/atomic.CompareAndSwapInt32()
      /usr/lib/google-golang/src/runtime/race_amd64.s:321 +0xb
  sync.(*Mutex).Lock()
      /usr/lib/google-golang/src/sync/mutex.go:74 +0x4d
  github.com/google/btree.(*FreeList).newNode()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:93 +0x3e
  github.com/google/btree.(*copyOnWriteContext).newNode()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:646 +0x7f0
  github.com/google/btree.(*BTree).ReplaceOrInsert()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:688 +0x7b1
  cloud.google.com/go/bigtable/bttest.(*table).mutableRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:1227 +0x3c4
  cloud.google.com/go/bigtable/bttest.(*server).MutateRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:795 +0x1bd
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func1()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:307 +0x564
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func2()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:316 +0x51

Previous write at 0x00c000517fa0 by goroutine 243:
  github.com/google/btree.NewFreeList()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:89 +0x644
  github.com/google/btree.New()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:128 +0x5dd
  cloud.google.com/go/bigtable/bttest.(*server).DropRowRange()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:264 +0x793
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func3()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:331 +0x14c

Goroutine 237 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:315 +0x5f0
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202

Goroutine 243 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:325 +0x664
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202
==================
==================
WARNING: DATA RACE
Read at 0x00c000517fa8 by goroutine 237:
  github.com/google/btree.(*FreeList).newNode()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:94 +0x55
  github.com/google/btree.(*copyOnWriteContext).newNode()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:646 +0x7f0
  github.com/google/btree.(*BTree).ReplaceOrInsert()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:688 +0x7b1
  cloud.google.com/go/bigtable/bttest.(*table).mutableRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:1227 +0x3c4
  cloud.google.com/go/bigtable/bttest.(*server).MutateRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:795 +0x1bd
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func1()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:307 +0x564
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func2()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:316 +0x51

Previous write at 0x00c000517fa8 by goroutine 243:
  github.com/google/btree.NewFreeList()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:89 +0x644
  github.com/google/btree.New()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:128 +0x5dd
  cloud.google.com/go/bigtable/bttest.(*server).DropRowRange()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:264 +0x793
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func3()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:331 +0x14c

Goroutine 237 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:315 +0x5f0
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202

Goroutine 243 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:325 +0x664
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202
==================
==================
WARNING: DATA RACE
Read at 0x00c000517fc8 by goroutine 237:
  github.com/google/btree.(*BTree).ReplaceOrInsert()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:690 +0x996
  cloud.google.com/go/bigtable/bttest.(*table).mutableRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:1227 +0x3c4
  cloud.google.com/go/bigtable/bttest.(*server).MutateRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:795 +0x1bd
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func1()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:307 +0x564
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func2()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:316 +0x51

Previous write at 0x00c000517fc8 by goroutine 243:
  github.com/google/btree.NewWithFreeList()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:136 +0x6e4
  github.com/google/btree.New()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:128 +0x6b6
  cloud.google.com/go/bigtable/bttest.(*server).DropRowRange()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:264 +0x793
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func3()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:331 +0x14c

Goroutine 237 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:315 +0x5f0
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202

Goroutine 243 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:325 +0x664
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202
==================
==================
WARNING: DATA RACE
Read at 0x00c0005ac470 by goroutine 237:
  github.com/google/btree.(*BTree).Get()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:819 +0x144
  cloud.google.com/go/bigtable/bttest.(*table).mutableRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:1213 +0xfd
  cloud.google.com/go/bigtable/bttest.(*server).MutateRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:795 +0x1bd
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func1()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:307 +0x564
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func2()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:316 +0x51

Previous write at 0x00c0005ac470 by goroutine 243:
  github.com/google/btree.NewWithFreeList()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:136 +0x6e4
  github.com/google/btree.New()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:128 +0x6b6
  cloud.google.com/go/bigtable/bttest.(*server).DropRowRange()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:264 +0x793
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func3()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:331 +0x14c

Goroutine 237 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:315 +0x5f0
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202

Goroutine 243 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:325 +0x664
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202
==================
==================
WARNING: DATA RACE
Read at 0x00c00026de20 by goroutine 237:
  github.com/google/btree.(*BTree).maxItems()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:636 +0x177
  github.com/google/btree.(*BTree).ReplaceOrInsert()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:694 +0x126
  cloud.google.com/go/bigtable/bttest.(*table).mutableRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:1227 +0x3c4
  cloud.google.com/go/bigtable/bttest.(*server).MutateRow()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:795 +0x1bd
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func1()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:307 +0x564
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func2()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:316 +0x51

Previous write at 0x00c00026de20 by goroutine 243:
  github.com/google/btree.NewWithFreeList()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:136 +0x6e4
  github.com/google/btree.New()
      /usr/local/google/home/coryan/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:128 +0x6b6
  cloud.google.com/go/bigtable/bttest.(*server).DropRowRange()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:264 +0x793
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func3()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:331 +0x14c

Goroutine 237 (running) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:315 +0x5f0
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202

Goroutine 243 (finished) created at:
  cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent()
      /usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:325 +0x664
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:1193 +0x202
==================
--- FAIL: TestTableRowsConcurrent (0.04s)
    testing.go:1092: race detected during execution of test
2021/06/02 23:05:42 Bad pattern "[": error parsing regexp: missing closing ]: `[)$`
2021/06/02 23:05:42 Bad pattern "[": error parsing regexp: missing closing ]: `[)$`
2021/06/02 23:05:42 Bad pattern "[": error parsing regexp: missing closing ]: `[)$`
2021/06/02 23:05:42 Bad pattern "[": error parsing regexp: missing closing ]: `[)$`
2021/06/02 23:05:42 Bad pattern "[": error parsing regexp: missing closing ]: `[)$`
2021/06/02 23:05:42 Bad pattern "[": error parsing regexp: missing closing ]: `[)$`
2021/06/02 23:05:42 Bad pattern "[": error parsing regexp: missing closing ]: `[)$`
2021/06/02 23:05:42 Bad pattern "a\\xC.+": error parsing regexp: invalid escape sequence: `\xC.`
FAIL
FAIL	cloud.google.com/go/bigtable/bttest	0.269s
FAIL
```

### CODE REVIEW

File: bigtable/bttest/inmem_test.go [hunk 1]
```diff
@@ -273,6 +273,71 @@ func TestSampleRowKeys(t *testing.T) {
...
+				Target: &btapb.DropRowRangeRequest_DeleteAllDataFromTable{DeleteAllDataFromTable: true},
+			}
+			if _, err = s.DropRowRange(ctx, req); err != nil {
+				t.Fatalf("Dropping all rows: %v", err)
+			}
+		}
+		finished <- true
+	}()
+	<-finished
+	<-finished
```
Comment (tritone) [inline bigtable/bttest/inmem_test.go:338]: Is a deadlock possible here? May be worth adding a timeout on the waiting, something like https://gobyexample.com/timeouts

**Review by tritone — COMMENTED** [review]
Very nice test, thanks @coryan ! @kolea2 or @crwilcox could you take a look as well?

File: bigtable/bttest/inmem_test.go (hunk 1 above)
Comment (coryan) [reply bigtable/bttest/inmem_test.go]: Done. But it is probably overkill: `go test` has a default timeout of 10m anyway.

**Review by kolea2 — APPROVED** [review]

**Comment by coryan** [comment]
Thanks for the reviews.  In case you do not know: I cannot merge into this repo, I cannot set the `automerge` tag either, I will need help to get this actually merged.

**Review by tritone — APPROVED** [review]

**Comment by coryan** [comment]
@tritone thanks for merging the code 🎉 

Do we need to take some action to get a new version of the emulator included in a future `gcloud` release?
