### PR TITLE
test(pubsub): cleanup ordered keys json integration test

### LINKED ISSUE #8572: pubsub: many tests failed
Many tests failed at the same time in this package.

* I will close this issue when there are no more failures in this package _and_
  there is at least one pass.
* No new issues will be filed for this package until this issue is closed.
* If there are already issues for individual test cases, I will close them when
  the corresponding test passes. You can close them earlier, if you prefer, and
  I won't reopen them while this issue is still open.

Here are the tests that failed:
* TestFlowControllerCancel (#7072)
* TestFlowControllerLargeRequest (#7073)
* TestFlowControllerNoStarve (#7074)
* TestFlowControllerSaturation (#7075)
* TestFlowControllerUnboundedCount (#7076)
* TestFlowControllerUnboundedCount2 (#7077)
* TestFlowControllerUnboundedBytes (#7078)
* TestIntegration_Admin
* TestIntegration_CancelReceive (#8195)
* TestIntegration_CreateSubscription_NeverExpire
* TestIntegration_UpdateSubscription
* TestIntegration_UpdateSubscription_ExpirationPolicy
* TestIntegration_UpdateTopicLabels
* TestIntegration_PublicTopic
* TestIntegration_Errors (#8431)
* TestIntegration_MessageStoragePolicy_TopicLevel
* TestIntegration_MessageStoragePolicy_ProjectLevel
* TestIntegration_CreateTopic_KMS
* TestIntegration_CreateTopic_MessageStoragePolicy
* TestIntegration_OrderedKeys_JSON (#8564)

-----
commit: dea40fdec71c201bac0a6e21e219070cc30e334b
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/9a068352-1ca4-4dfe-a2f3-4a06314b9a01), [Sponge](http://sponge2/9a068352-1ca4-4dfe-a2f3-4a06314b9a01)
status: failed

### PR DESCRIPTION
**Pull request by hongalex**
This fixes an issue where too many goroutines were being created in short period of time in the integration test. Publish result is implicitly checked by counting the messages after they've been received.

In addition, the subscription was being deleted before Receive exits. This adds additional channel to signal Receive is exited before the deferred delete happens.

Fixes #8572 #8564

### CODE REVIEW

File: pubsub/integration_test.go [hunk 1]
```diff
@@ -1263,23 +1263,18 @@ func TestIntegration_OrderedKeys_JSON(t *testing.T) {
...
 			OrderingKey: key,
 		})
-		go func() {
-			_, err := r.Get(ctx)
-			if err != nil {
-				// Can't fail inside goroutine, so just log the error.
-				t.Logf("publish error for message(%s): %v", msg, err)
-			}
-		}()
 		wg.Add(1)
```
Comment (shollyman) [inline pubsub/integration_test.go:1270]: The waitgroup pattern here looks a little racy at a glance.  It looks like you can get to zero in the wg multiple times if the publish and subscribes keep up with another, which may fire the done early?  The test doesn't seem to compare it the publish/subscribe counts are aligned.

Comment (hongalex) [reply pubsub/integration_test.go:1270]: I believe that all of the `wg.Add(1)` calls will always happen before the goroutine that calls `Receive` is executed (where `wg.Done` is called). This should prevent reaching zero in the waitgroup multiple times.

Comment (shollyman) [reply pubsub/integration_test.go:1270]: Yeah, appears I misread this initially.  Thanks for confirming.

**Review by shollyman — APPROVED** [review]
