### PR TITLE
fix(bigtable): disable connection pooling when emulator is set

### LINKED ISSUE #14480: bigtable: ConnectionPool doesn't work with emulator
## Environment

* Go 1.25
* cloud.google.com/go/bigtable: v1.46.0

## Code and Dependencies

```go
import "cloud.google.com/go/bigtable"

bigtable.NewClient(...)
```

<details>
  <summary>go.mod</summary>

```text
module modname

go 1.25.0

require (
   // ...
)
```

</details>

## Expected behavior

The connection pool should work with the emulator (i.e.,`BIGTABLE_EMULATOR_HOST` is set)

## Actual behavior

`bigtable_connpool:  connection factory prime failed: factory prime failed after 3
attempts: rpc error: code = Canceled desc = grpc: the client connection is closing`

## Screenshots

e.g. A chart showing how messages are slow. Delete if not necessary.

## Additional context

With v1.25.0, the connection pool was by default disabled, but with v1.26.0 it's now turned on ([code](https://github.com/googleapis/google-cloud-go/blob/bigtable/v1.46.0/bigtable/internal/option/option.go#L195-L206)).

Setting `CBT_BIGTABLE_CONN_POOL=false` works as a workaround, but ideally this shouldn't be needed.

### PR DESCRIPTION
**Pull request by bhshkh**
#### Summary
This PR fixes issue #14480 . The fix automatically disables the custom connection pool whenever the `BIGTABLE_EMULATOR_HOST` environment variable is detected.

#### Root Cause
In recent versions (v1.26.0+), the custom Bigtable connection pool is enabled by default for production traffic . However, when `BIGTABLE_EMULATOR_HOST` is set, the client library initializes a single shared `*grpc.ClientConn` . 

The custom connection pool expects to manage the lifecycle of multiple unique channels. Because the emulator uses a single pre-dialed connection, the pool's attempt to "prime" or manage multiple internal connections results in conflicts. Specifically, if the pool attempts to close or recycle a connection wrapper, it inadvertently closes the shared underlying gRPC connection for all other members of the pool, leading to errors such as `rpc error: code = Canceled desc = grpc: the client connection is closing`.

#### Changes
Modified `google3/third_party/golang/cloud_google_com/go/bigtable/v/v1/internal/option/option.go`:
- Updated `EnableBigtableConnectionPool` to check for the `BIGTABLE_EMULATOR_HOST` environment variable .
- If the emulator host is set, the function now returns `false`, ensuring the client falls back to the standard connection logic.

This change automates the current manual workaround of setting `CBT_BIGTABLE_CONN_POOL=false` when using the emulator .

Fixes: #14480

### CODE REVIEW

File: bigtable/integration_test.go [hunk 1]
```diff
@@ -487,6 +488,23 @@ func TestIntegration_NoopMetricsProvider(t *testing.T) {
...
+		t.Fatalf("failed to start bttest server: %v", err)
+	}
+	defer srv.Close()
+
+	t.Setenv("BIGTABLE_EMULATOR_HOST", srv.Addr)
+
+	ctx := context.Background()
+	client, err := NewClient(ctx, "test-project", "test-instance")
+	if err != nil {
+		t.Fatalf("NewClient failed with emulator host: %v", err)
```
Comment (hongalex) [inline bigtable/integration_test.go:503]: Is `NewClient` expected to fail prior to this change? Wanted to check since I'm not sure if the dial fails or the RPCs fail later on.

Comment (bhshkh) [reply bigtable/integration_test.go:503]: NewClient fails:

```
--- FAIL: TestIntegration_NewClientWithEmulatorHost (0.12s)
    /usr/local/google/home/bahaaiman/Documents/cfdb-workspace-01/fspq/google-cloud-go/bigtable/integration_test.go:503: NewClient failed with emulator host: bigtable_connpool:  connection factory prime failed: factory prime failed after 3 attempts: rpc error: code = Canceled desc = grpc: the client connection is closing
FAIL
```

**Review by shollyman — APPROVED** [review]

**Review by hongalex — APPROVED** [review]
