### PR TITLE
chore(datastore): integration test fix

### LINKED ISSUE #6938: datastore: TestIntegration_GetWithReadTime failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 924074139a086aec7f12572d05909ee0b54e21f5
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/c884c352-68b8-45a9-9578-2d8eb4b16957), [Sponge](http://sponge2/c884c352-68b8-45a9-9578-2d8eb4b16957)
status: failed
<details><summary>Test output</summary><br><pre>    integration_test.go:222: client.Get: rpc error: code = InvalidArgument desc = timestamp cannot have more than microseconds precision</pre></details>

### LINKED ISSUE #6939: datastore: TestIntegration_GetMulti failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 924074139a086aec7f12572d05909ee0b54e21f5
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/c884c352-68b8-45a9-9578-2d8eb4b16957), [Sponge](http://sponge2/c884c352-68b8-45a9-9578-2d8eb4b16957)
status: failed
<details><summary>Test output</summary><br><pre>    integration_test.go:330: client.GetMulti got *status.Error, expected MultiError</pre></details>

### PR DESCRIPTION
**Pull request by telpirion**
Fixes #6938
Fixes #6939

### CODE REVIEW

File: datastore/integration_test.go [hunk 1]
```diff
@@ -225,6 +225,9 @@ func TestIntegration_GetWithReadTime(t *testing.T) {
 		t.Fatalf("Transaction.Commit: %v\n", err)
 	}
 
+	// We need to wait a few seconds to allow eventual consistency to catch up.
+	time.Sleep(time.Duration(10 * math.Pow(10, 9)))
```
Comment (codyoss) [inline datastore/integration_test.go:229]: This time is not really readable, nor the line below. Please do something like:

```
time.Sleep(10 * time.Second)
```

Also, we are are already retrying, why do we need to sleep as well? The retry will sleep on failure, right?

**Review by codyoss — CHANGES_REQUESTED** [review]

File: datastore/integration_test.go (hunk 1 above)
Comment (telpirion) [reply datastore/integration_test.go:229]: (Thanks for the tip about expressing seconds :)! I had forgotten about that constant.)

It seems that we need more time for the database to catch up with the test. It's hard for me to determine what is the correct fix here, since my local environment differs so much from the integration environment.

I'll try to increase the sleep on the retry to see if that fixes this issue and delete this first call to sleep.

**Review by codyoss — APPROVED** [review]
