### PR TITLE
fix(bigquery): fetch dst table for jobs when readings with Storage API

### LINKED ISSUE #7322: bigquery: TestIntegration_StorageReadQueryMorePages failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: c88fbdf299205e8118b347430cf66540ffa68b27
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/65dadf7a-1064-4ec8-aafa-1373f7406e21), [Sponge](http://sponge2/65dadf7a-1064-4ec8-aafa-1373f7406e21)
status: failed
<details><summary>Test output</summary><br><pre>    storage_integration_test.go:280: expected query to use Storage API</pre></details>

### PR DESCRIPTION
**Pull request by alvarowolfx**
Pay the cost of re-fetching job information when using the Storage API, to guarantee availability of Destination Table. Some cases were not covered before, like when the Job take a long time to run.

Fixes #7322

### CODE REVIEW

File: bigquery/storage_integration_test.go [hunk 1]
```diff
@@ -319,21 +321,28 @@ func TestIntegration_StorageReadCancel(t *testing.T) {
...
 			t.Fatalf("failed to fetch via storage API: %v", err)
 		}
+		rowsRead++
+		if rowsRead > 1000 {
+			cancel()
+		}
 	}
 	// resources are cleaned asynchronously
-	time.Sleep(500 * time.Millisecond)
+	time.Sleep(1 * time.Second)
```
Comment (shollyman) [inline bigquery/storage_integration_test.go:345]: nit: don't need to multiply by 1

**Review by shollyman — APPROVED** [review]
