### PR TITLE
test(storage): use current googler email in integration test

### LINKED ISSUE #5051: storage: TestIntegration_ACL failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: d15b1e55bb2812d65ad397b53a39d771a5743122
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/afa6d53f-aebd-4b14-855b-046a7a7b09d7), [Sponge](http://sponge2/afa6d53f-aebd-4b14-855b-046a7a7b09d7)
status: failed
<details><summary>Test output</summary><br><pre>    integration_test.go:2238: Error while deleting bucket ACL rule: googleapi: Error 400: Unknown user email addresss: jbd@google.com, invalid</pre></details>

### PR DESCRIPTION
**Pull request by crwilcox**
Fixes #5051

### CODE REVIEW

**Review by codyoss — APPROVED** [review]

File: storage/integration_test.go [hunk 1]
```diff
@@ -2213,8 +2213,8 @@ func TestIntegration_ACL(t *testing.T) {
 		t.Errorf("default ACL: could not delete entity %s", entity)
 	}
 
-	entity2 := ACLEntity("user-jbd@google.com")
-	rule2 := ACLRule{Entity: entity2, Role: RoleReader, Email: "jbd@google.com"}
+	entity2 := ACLEntity("user-crwilcox@google.com")
```
Comment (tritone) [inline storage/integration_test.go:2216]: Is there another more stable test identity/email that is used for these tests elsewhere? Not to imply that you won't be around indefinitely 😄 

Also wondering if it's worth having a test with a specific email-- we might be able to just use another predefined role.

Comment (tritone) [reply storage/integration_test.go:2216]: I see https://github.com/googleapis/google-cloud-go/blob/master/storage/integration_test.go#L452 , let's do the same here?

Comment (crwilcox) [reply storage/integration_test.go:2216]: Hey now, I am gonna work at google and live *forever*. Obviously 😅 


https://github.com/googleapis/google-cloud-go/blob/master/storage/acl.go#L41 does define a few options, perhaps we can use a group instead?

Comment (frankyn) [reply storage/integration_test.go:2216]: Could we use `project-owners-TEST_PROJECT_NUMBER` ==> `project-owners-123456789` instead? 

https://cloud.google.com/storage/docs/access-control/lists#scopes

Comment (crwilcox) [reply storage/integration_test.go]: I set it to allAuthenticatedUsers, since that should be more-or-less permanent. are you implying though we could use an arbitrary product, or that we could use a known project?

Comment (frankyn) [reply storage/integration_test.go]: I would prefer specific to the test project which you should be able to get the project number: using `allAuthenticatedUsers` is almost like `allUsers` except `This special scope identifier represents anyone who is authenticated with a Google account`.

Comment (crwilcox) [reply storage/integration_test.go]: As part of test setup we do require the following var

```
- `GCLOUD_TESTS_GOLANG_PROJECT_ID`: Developers Console project's ID (e.g.
bamboo-shift-455) for the general project.
```

I can make it use that as the principal.

Comment (frankyn) [reply storage/integration_test.go]: @tritone clarified that it's acceptable to keep allAuthenticatedUsers in this case. Please ignore my concern.
