### PR TITLE
test(pubsub/v2): fix streaming pull mock test race condition

### LINKED ISSUE #13748: pubsub: TestStreamingPullBasic failed
Note: #9605 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 1cf600d68b604984ffcf475d495b5e4e9eee8e68
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/89d923fd-c135-4bee-8a12-c334ef7332fd), [Sponge](http://sponge2/89d923fd-c135-4bee-8a12-c334ef7332fd)
status: failed

### PR DESCRIPTION
**Pull request by hongalex**
The same changes are mirrored between `pubsub` and `pubsub/v2`

Fixes #13748

### CODE REVIEW

**Review by shollyman — APPROVED** [review]

File: pubsub/v2/mock_test.go [hunk 1]
```diff
@@ -99,11 +100,24 @@ func (s *mockServer) wait() {
...
+}
+
 func (s *mockServer) StreamingPull(stream pb.Subscriber_StreamingPullServer) error {
-	s.wg.Add(1)
+	s.mu.Lock()
+	if s.stopped {
+		s.mu.Unlock()
+		return errors.New("mock server stopped")
+	}
+	// Add 2 to the WaitGroup: one for this main loop and one for the receive goroutine below.
```
Comment (AlexGhiondea) [inline pubsub/v2/mock_test.go]: Does it make sense to keep the adds separate and have them guarded by the same lock? That way if someone either looks at the code in the future, or something changes, it is easy to understand?

I am also not entirely sure about the interaction of the Done() call with the Add(2) here -- can those lead to a deadlock?

Comment (hongalex) [reply pubsub/v2/mock_test.go]: I think the comment was my attempt to disambiguate, but since it still causes some confusion, I'll just revert to the previous behavior.

I'm not seeing how the deadlock scenario could play out. For this streaming pull lifespan, the server will Add(2) (or Add(1) twice) before continuing to do anything else. Then, further calls to `server.wait` will complete only complete when both the send and receive flows are done (received an error on stream). A deadlock would only be possible if you called Add more times than Done, or if the program panics from calling `Done` more times than await.
