### PR TITLE
fix(spanner): inject "x-goog-spanner-request-id" into outgoing client context

### LINKED ISSUE #11543: spanner: x-goog-spanner-request-id generated but not propagated in RPC to Google's Frontend server
## Client

Spanner

Coming here to make a reference, that despite generating and testing out to ensure that x-goog-spanner-request-id is correctly generated, it wasn't being propagated to Google's Frontend server as reported to me offline.

## Diagnosis
The problem is that the outgoing context isn't injected with the appropriate header in our interceptor.

### PR DESCRIPTION
**Pull request by odeke-em**
Injects metadata derived from the associated gax.CallOptions that were correctly being generated and tested, but accidentally not injected into the outgoing context.

Fixes #11543

### CODE REVIEW

File: spanner/request_id_header.go [hunk 1]
```diff
@@ -137,7 +138,12 @@ func gRPCCallOptionsToRequestID(opts []grpc.CallOption) (reqID requestID, found
 func (wr *requestIDHeaderInjector) interceptUnary(ctx context.Context, method string, req, reply any, cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption) error {
 	// It is imperative to search for the requestID before the call
 	// because gRPC's internals will consume the headers.
-	reqID, foundRequestID := gRPCCallOptionsToRequestID(opts)
+	mdWithRequestID, reqID, foundRequestID := gRPCCallOptionsToRequestID(opts)
+	if !foundRequestID {
+		panic(fmt.Sprintf("missing %q request header for %q", xSpannerRequestIDHeader, method))
```
Comment (rahul2393) [inline spanner/request_id_header.go:143]: Do we want to panic here? or do a noop?

Comment (odeke-em) [reply spanner/request_id_header.go:143]: You know I wondered about that too earlier, but a panic allows us to proactively find any bugs.

Comment (rahul2393) [reply spanner/request_id_header.go:143]: I think logging error/warning should be good here, since we don't to stop the world for our customers because of tracing?

Comment (odeke-em) [reply spanner/request_id_header.go:143]: I'll just then insert a TODO that can then be picked up for as we please later on.

Comment (odeke-em) [reply spanner/request_id_header.go]: Done, thanks!

File: spanner/request_id_header.go [hunk 2]
```diff
@@ -174,7 +180,12 @@ type requestIDHeaderInjector int
 func (wr *requestIDHeaderInjector) interceptStream(ctx context.Context, desc *grpc.StreamDesc, cc *grpc.ClientConn, method string, streamer grpc.Streamer, opts ...grpc.CallOption) (grpc.ClientStream, error) {
 	// It is imperative to search for the requestID before the call
 	// because gRPC's internals will consume the headers.
-	reqID, foundRequestID := gRPCCallOptionsToRequestID(opts)
+	mdWithRequestID, reqID, foundRequestID := gRPCCallOptionsToRequestID(opts)
+	if !foundRequestID {
+		panic(fmt.Sprintf("missing %q request header for %q", xSpannerRequestIDHeader, method))
```
[the remark this answers is not in the document]
Comment (odeke-em) [reply spanner/request_id_header.go]: Done, thanks!

**Review by olavloite — APPROVED** [review]
Approving this to ensure progress. But can we add a test in a follow-up PR that fails without this change?
