### PR TITLE
fix(spanner): avoid desructive context augmentation that dropped all headers

### LINKED ISSUE #11656: Spanner: x-goog-spanner-request-id related changes have caused other headers not to be forwarded
Reported offline in a bug report by Simil and team, after the reported changes, a bunch of headers aren’t being forwarded. This is an issue for myself to diagnose the problem and also to write tests for other headers so that in the future breakages shall be noticed.

### PR DESCRIPTION
**Pull request by odeke-em**
This change fixes a destructive context operation that dropped all prior headers, metadata.NewOutgoingContext sadly doesn't document that it doesn't reuse the input conext negating the expectation in Go that building from a parent context brings along the prior keys and metadata. While here, this chhange adds a regression test to ensure that in the future, any dropped or lost metadata will be reported during development.

Fixes #11656

### CODE REVIEW

File: spanner/regression_test.go [hunk 1]
```diff
@@ -0,0 +1,214 @@
...
+		t.Fatal(err)
+	}
+	defer sc.Close()
+
+	// 2. Perform a simple "SELECT 1" to trigger both unary and streaming gRPC calls.
+	sqlSELECT1 := "SELECT 1"
+	resultSet := &sppb.ResultSet{
+		Rows: []*structpb.ListValue{
+			{Values: []*structpb.Value{
+				{Kind: &structpb.Value_NumberValue{NumberValue: 1}},
```
Comment (olavloite) [inline spanner/regression_test.go:104]: nit: not directly relevant to this test, as it does not read the value, but this encoding is not correct. INT64 values are encoded as string values. NumberValue is only used for FLOAT32 and FLOAT64. But it would be good to fix that here, as others might copy-paste this test later and run into unexpected errors when they try to read the data.
(If you want to verify that it fails: Try to do a `row.Scan(..)` in the loop below that iterates over the rows.)

File: spanner/regression_test.go [hunk 2]
```diff
@@ -0,0 +1,214 @@
...
+	oi.unaryHeaders = append(oi.unaryHeaders, &methodAndMetadata{usi.FullMethod, md})
+	return handler(ctx, req)
+}
+
+// This is a regression test to assert that all the expected headers are propagated
+// along to the final gRPC server avoiding scenarios where headers got dropped from a
+// destructive context augmentation call.
+// Please see https://github.com/googleapis/google-cloud-go/issues/11656
+func TestAllHeadersForwardedAppropriately(t *testing.T) {
+	if isMultiplexEnabled {
```
Comment (olavloite) [inline spanner/regression_test.go:69]: Instead of skipping if multiplexed sessions are enabled, can we disable multiplexed sessions during this test, and re-enable after the test?
Or alternatively only check for the requests that we know will be present regardless whether multiplexed sessions are being used or not (meaning: Only check for the presence of `BeginTransaction` and `ExecuteSql`, as those requests will be there in both cases.) The latter solution would also allow this test to be parallel.

**Review by olavloite — APPROVED** [review]
LGTM, with some nits on the test. We can pick that up in a follow-up PR as well if we want to ship this ASAP.

File: spanner/regression_test.go (hunk 2 above)
Comment (odeke-em) [reply spanner/regression_test.go]: @olavloite done, thanks and please take a look.

File: spanner/regression_test.go (hunk 1 above)
Comment (odeke-em) [reply spanner/regression_test.go]: Gotcha and thanks, done! Please take a look.

**Comment by odeke-em** [comment]
@olavloite kindly help me re-run the bots!
